<%@page errorPage="/includes/error.jsp"%>
<%@include file="/includes/validateUser.jsp"%>
<%

%>
<form name="transactionForm" id="transactionForm" method="POST" action='<c:url value="/healthrecord/updateTransaction.do"/>?ts=<%=getTs()%>' onclick="setSaveButton(event);" onkeyup="setSaveButton(event);">
    <bean:define id="transaction" name="be.mxs.webapp.wl.session.SessionContainerFactory.WO_SESSION_CONTAINER" property="currentTransactionVO"/>
    <input type="hidden" id="transactionId" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.transactionId" value="<bean:write name="transaction" scope="page" property="transactionId"/>"/>
    <input type="hidden" id="transactionType" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.transactionType" value="<bean:write name="transaction" scope="page" property="transactionType"/>"/>
    <input type="hidden" id="serverId" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.serverId" value="<bean:write name="transaction" scope="page" property="serverId"/>"/>
    <input type="hidden" readonly name="be.mxs.healthrecord.updateTransaction.actionForwardKey" value="/healthrecord/manageClinicalExamination.do?be.mxs.healthrecord.createTransaction.transactionType=<bean:write name="transaction" scope="page" property="transactionType"/>&be.mxs.healthrecord.transaction_id=currentTransaction"/>
    <input type="hidden" readonly name="subClass" value=".NEURO.PSYCHO"/>
    <input type="hidden" readonly name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CONTEXT_DEPARTMENT" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CONTEXT_DEPARTMENT" translate="false" property="value"/>"/>
    <input type="hidden" readonly name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CONTEXT_CONTEXT" translate="false" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CONTEXT_CONTEXT" translate="false" property="value"/>"/>
    <%
        if (session.getAttribute("sessionCounter")==null){
            session.setAttribute("sessionCounter",new Integer(0));
        }
        else {
            session.setAttribute("sessionCounter",new Integer(((Integer)session.getAttribute("sessionCounter")).intValue()+1));
        }
        session.setAttribute("sessionURL","/healthrecord/template.jsp?be.mxs.healthrecord.transaction_id=currentTransaction&Page="+customerInclude("/healthrecord/neuro.jsp")+"&message=true");
        if (request.getParameter("message")!=null){
            out.print("<script>alert('"+getTran("Web.Occup","medwan.common.do-not-use-back",sWebLanguage)+"');</script>");
        }
    %>
<script>
  function setTrue(itemType){
    var fieldName;
    fieldName = "currentTransactionVO.items.<ItemVO[hashCode="+itemType+"]>.value";
    document.all[fieldName].value = "medwan.common.true";
  }

  function setFalse(itemType){
    var fieldName;
    fieldName = "currentTransactionVO.items.<ItemVO[hashCode="+itemType+"]>.value";
    document.all[fieldName].value = "medwan.common.false";
  }
</script>
<br>
<%-- NEUROLOGIE ----------------------------------------------------------------------------------%>
<table border='0' width='100%' cellspacing="1" cellpadding="0" class="list">
    <tr class="admin">
        <td colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.neurologie",sWebLanguage)%></td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.force-loss-arm",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <input <%=setRightClick("ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_ARM_RIGHT")%> type="checkbox" id="neu-c1" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_ARM_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_ARM_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"neu-c1")%>
            <input <%=setRightClick("ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_ARM_LEFT")%> type="checkbox" id="neu-c2" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_ARM_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_ARM_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"neu-c2")%>
        </td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.force-loss-leg",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <input <%=setRightClick("ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_LEG_RIGHT")%> type="checkbox" id="neu-c3" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_LEG_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_LEG_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"neu-c3")%>
            <input <%=setRightClick("ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_LEG_LEFT")%> type="checkbox" id="neu-c4" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_LEG_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_LEG_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"neu-c4")%></td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.sensitivity-loss-arm",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <input <%=setRightClick("ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_ARM_RIGHT")%> type="checkbox" id="neu-c5" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_ARM_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_ARM_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"neu-c5")%>
            <input <%=setRightClick("ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_ARM_LEFT")%> type="checkbox" id="neu-c6" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_ARM_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_ARM_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"neu-c6")%>
        </td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.sensitivity-loss-leg",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <input <%=setRightClick("ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_LEG_RIGHT")%> type="checkbox" id="neu-c7" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_LEG_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_LEG_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"neu-c7")%>
            <input <%=setRightClick("ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_LEG_LEFT")%> type="checkbox" id="neu-c8" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_LEG_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_LEG_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"neu-c8")%>
        </td>
    </tr>
    <tr>
        <td class="clinical" colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%></td>
    </tr>
    <tr class="gray">
        <td colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.neuro.diminished-reflexes",sWebLanguage)%></td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.knee-reflex",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_KNEE_REFLEX_RIGHT")%> type="checkbox" id="neu-c9" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_KNEE_REFLEX_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_KNEE_REFLEX_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"neu-c9")%>
            <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_KNEE_REFLEX_LEFT")%> type="checkbox" id="neu-c10" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_KNEE_REFLEX_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_KNEE_REFLEX_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"neu-c10")%>
        </td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("web.occup","medwan.healthrecord.neuro.hippocratic-chord-reflex",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HIPPOCRATIC_CORDA_REFLEX_RIGHT")%> type="checkbox" id="neu-c11" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HIPPOCRATIC_CORDA_REFLEX_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HIPPOCRATIC_CORDA_REFLEX_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"neu-c11")%>
            <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HIPPOCRATIC_CORDA_REFLEX_LEFT")%> type="checkbox" id="neu-c12" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HIPPOCRATIC_CORDA_REFLEX_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HIPPOCRATIC_CORDA_REFLEX_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"neu-c12")%>
        </td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.biceps-reflex",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_BICEPS_REFLEX_RIGHT")%> type="checkbox" id="neu-c13" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_BICEPS_REFLEX_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_BICEPS_REFLEX_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"neu-c13")%>
            <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_BICEPS_REFLEX_LEFT")%> type="checkbox" id="neu-c14" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_BICEPS_REFLEX_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_BICEPS_REFLEX_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"neu-c14")%>
        </td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.triceps-reflex",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_TRICEPS_REFLEX_RIGHT")%> type="checkbox" id="neu-c15" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_TRICEPS_REFLEX_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_TRICEPS_REFLEX_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"neu-c15")%>
            <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_TRICEPS_REFLEX_LEFT")%> type="checkbox" id="neu-c16" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_TRICEPS_REFLEX_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_TRICEPS_REFLEX_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"neu-c16")%>
        </td>
    </tr>
    <tr class="gray">
        <td colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.neuro.sensitivity-disorders",sWebLanguage)%></td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.arm",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_ARM_RIGHT")%> type="checkbox" id="neu-c17" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_ARM_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_ARM_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"neu-c17")%>
            <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_ARM_LEFTT")%> type="checkbox" id="neu-c18" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_ARM_LEFTT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_ARM_LEFTT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"neu-c18")%>
        </td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.leg",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_LEG_RIGHT")%> type="checkbox" id="neu-c19" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_LEG_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_LEG_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"neu-c19")%>
            <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_LEG_LEFT")%> type="checkbox" id="neu-c20" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_LEG_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_LEG_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"neu-c20")%>
        </td>
    </tr>
    <tr class="gray">
        <td colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.neuro.coordination-and-balance",sWebLanguage)%></td>
    </tr>
    <tr>
        <td class="admin" width="<%=sTDAdminWidth%>"/>
        <td class="admin2" width="250"><input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_ROMBERG")%> type="checkbox" id="neu-c21" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_ROMBERG" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_ROMBERG;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.romberg",sWebLanguage,"neu-c21")%></td>
        <td class="admin2" width="250"><input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_TOE_WALKING")%> type="checkbox" id="neu-c22" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_TOE_WALKING" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_TOE_WALKING;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.toe-walking",sWebLanguage,"neu-c22")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HEEL_WALKING")%> type="checkbox" id="neu-c23" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HEEL_WALKING" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HEEL_WALKING;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.heel-walking",sWebLanguage,"neu-c23")%></td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.finger-nose",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FINGER_NOSE_TEST_RIGHT")%> type="checkbox" id="neu-c24" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FINGER_NOSE_TEST_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FINGER_NOSE_TEST_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"neu-c24")%>
            <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FINGER_NOSE_TEST_LEFT")%> type="checkbox" id="neu-c25" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FINGER_NOSE_TEST_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FINGER_NOSE_TEST_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"neu-c25")%>
        </td>
    </tr>
    <tr>
        <td class="clinical" colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></td>
    </tr>
    <tr>
        <td class="admin" rowspan="4"/>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_EPILEPSY")%> type="checkbox" id="neu-c26" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_EPILEPSY" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_EPILEPSY;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.epilepsy",sWebLanguage,"neu-c26")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_SPEECH_DISORDER")%> type="checkbox" id="neu-c27" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_SPEECH_DISORDER" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_SPEECH_DISORDER;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.speech-disorders",sWebLanguage,"neu-c27")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_SENSITIVITY_DISORDER")%> type="checkbox" id="neu-c28" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_SENSITIVITY_DISORDER" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_SENSITIVITY_DISORDER;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.sensitivity-disorders",sWebLanguage,"neu-c28")%></td>
    </tr>
    <tr>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_TREMOR")%> type="checkbox" id="neu-c29" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_TREMOR" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_TREMOR;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.tremor",sWebLanguage,"neu-c29")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_MUSCULAR_ATROFIA")%> type="checkbox" id="neu-c30" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_MUSCULAR_ATROFIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_MUSCULAR_ATROFIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.musscle-atrophia",sWebLanguage,"neu-c30")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_HEADACHE")%> type="checkbox" id="neu-c31" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_HEADACHE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_HEADACHE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.headaches",sWebLanguage,"neu-c31")%></td>
    </tr>
    <tr>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_TIA")%> type="checkbox" id="neu-c32" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_TIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_TIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.tia",sWebLanguage,"neu-c32")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_CVA")%> type="checkbox" id="neu-c33" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_CVA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_CVA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.cva",sWebLanguage,"neu-c33")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_PARKINSON")%> type="checkbox" id="neu-c34" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_PARKINSON" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_PARKINSON;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.parkinson",sWebLanguage,"neu-c34")%></td>
    </tr>
    <tr>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_NUERITIS_POLYNEURITIS")%> type="checkbox" id="neu-c35" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_NUERITIS_POLYNEURITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_NUERITIS_POLYNEURITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.neuritis-polyneuritis",sWebLanguage,"neu-c35")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_MENTAL_RETARDATION")%> type="checkbox" id="neu-c36" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_MENTAL_RETARDATION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_MENTAL_RETARDATION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.mental-retardation",sWebLanguage,"neu-c36")%></td>
        <td class="admin2" colspan="2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_COMMOTION")%> type="checkbox" id="neu-c37" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_COMMOTION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_COMMOTION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.commotion",sWebLanguage,"neu-c37")%></td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.common.remark",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <textarea onKeyup="resizeTextarea(this,10);limitChars(this,255);" <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_OTHER")%> class="text" rows="2" cols="80" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_OTHER" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_OTHER" property="value"/></textarea>
        </td>
    </tr>
</table>
<br>
<!-- PSYCHO --------------------------------------------------------------------------------------->
<table border='0' width='100%' cellspacing="1" cellpadding="0" class="list">
    <tr class="admin">
        <td colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.psychosocial",sWebLanguage)%></td>
    </tr>
    <tr>
        <td class="admin"/>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_PSYCHO_ANAMNESIS_FATIGUE")%> type="checkbox" id="neu-c38" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_ANAMNESIS_FATIGUE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_ANAMNESIS_FATIGUE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.fatigue",sWebLanguage,"neu-c38")%></td>
        <td class="admin2" colspan="2"><input <%=setRightClick("ITEM_TYPE_PSYCHO_ANAMNESIS_STRESSED")%> type="checkbox" id="neu-c39" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_ANAMNESIS_STRESSED" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_ANAMNESIS_STRESSED;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.stressed",sWebLanguage,"neu-c39")%></td>
    </tr>
    <tr>
        <td class="clinical" colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></td>
    </tr>
    <tr>
        <td class="admin" width="<%=sTDAdminWidth%>" rowspan="7"/>
        <td class="admin2" width="250"><input <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSIS_DEPRESSION")%> type="checkbox" id="neu-c40" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_DEPRESSION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_DEPRESSION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.depression",sWebLanguage,"neu-c40")%></td>
        <td class="admin2" width="250"><input <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSIS_BURN_OUT")%> type="checkbox" id="neu-c41" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_BURN_OUT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_BURN_OUT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.burn-out",sWebLanguage,"neu-c41")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSIS_GENERAL_STRESS")%> type="checkbox" id="neu-c42" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_GENERAL_STRESS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_GENERAL_STRESS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.general-stress",sWebLanguage,"neu-c42")%></td>
    </tr>
    <tr>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSIS_MOBBING")%> type="checkbox" id="neu-c43" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_MOBBING" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_MOBBING;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.mobbing",sWebLanguage,"neu-c43")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSISPHYSICAL_VIOLENCE")%> type="checkbox" id="neu-c44" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSISPHYSICAL_VIOLENCE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSISPHYSICAL_VIOLENCE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.physical-violence",sWebLanguage,"neu-c44")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSIS_SEXUAL_INTIMIDATION")%> type="checkbox" id="neu-c45" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_SEXUAL_INTIMIDATION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_SEXUAL_INTIMIDATION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.sexual-intimidation",sWebLanguage,"neu-c45")%></td>
    </tr>
    <tr>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSIS_ALCOHOL")%> type="checkbox" id="neu-c46" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_ALCOHOL" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_ALCOHOL;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.alcohol",sWebLanguage,"neu-c46")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSIS_DRUGS")%> type="checkbox" id="neu-c47" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_DRUGS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_DRUGS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.drugs",sWebLanguage,"neu-c47")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSIS_SLEEP_DISORDER")%> type="checkbox" id="neu-c48" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_SLEEP_DISORDER" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_SLEEP_DISORDER;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.sleep-disorder",sWebLanguage,"neu-c48")%></td>
    </tr>
    <tr>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSIS_PSYCHO_PHARMACA")%> type="checkbox" id="neu-c49" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_PSYCHO_PHARMACA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_PSYCHO_PHARMACA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.psychopharmaca",sWebLanguage,"neu-c49")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSIS_HYPERVENTILATION")%> type="checkbox" id="neu-c50" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_HYPERVENTILATION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_HYPERVENTILATION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.hyperventilation",sWebLanguage,"neu-c50")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSIS_FEAR_NEUROSIS")%> type="checkbox" id="neu-c51" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_FEAR_NEUROSIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_FEAR_NEUROSIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.fear-neurosis",sWebLanguage,"neu-c51")%></td>
    </tr>
    <tr>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSIS_SUICIDAL_TENDENCY")%> type="checkbox" id="neu-c52" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_SUICIDAL_TENDENCY" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_SUICIDAL_TENDENCY;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.suicidal-tendency",sWebLanguage,"neu-c52")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSIS_NERVOUSNESS")%> type="checkbox" id="neu-c53" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_NERVOUSNESS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_NERVOUSNESS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.nervousness",sWebLanguage,"neu-c53")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSIS_MANIC_DEPRESSION")%> type="checkbox" id="neu-c54" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_MANIC_DEPRESSION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_MANIC_DEPRESSION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.manic-depression",sWebLanguage,"neu-c54")%></td>
    </tr>
    <tr>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSIS_ADAPTATION_DISORDER")%> type="checkbox" id="neu-c55" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_ADAPTATION_DISORDER" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_ADAPTATION_DISORDER;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.adaptation-disorder",sWebLanguage,"neu-c55")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSIS_TICS")%> type="checkbox" id="neu-c56" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_TICS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_TICS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.tics",sWebLanguage,"neu-c56")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSIS_PSYCHO_SOMATIC_DISORDER")%> type="checkbox" id="neu-c57" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_PSYCHO_SOMATIC_DISORDER" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_PSYCHO_SOMATIC_DISORDER;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.psychosomatic-disorders",sWebLanguage,"neu-c57")%></td>
    </tr>
    <tr>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSIS_POST_PARTUM_DEPRESSION")%> type="checkbox" id="neu-c58" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_POST_PARTUM_DEPRESSION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_POST_PARTUM_DEPRESSION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.post-partum-depression",sWebLanguage,"neu-c58")%></td>
        <td class="admin2" colspan="2"><input <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSIS_ANOREXIA_NERVOSA")%> type="checkbox" id="neu-c59" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_ANOREXIA_NERVOSA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_ANOREXIA_NERVOSA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.psycho.anorexia-nervosa",sWebLanguage,"neu-c59")%></td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.common.remark",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <textarea onKeyup="resizeTextarea(this,10);limitChars(this,255);" <%=setRightClick("ITEM_TYPE_PSYCHO_DIAGNOSIS_OTHER")%> class="text" rows="2" cols="80" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_OTHER" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_PSYCHO_DIAGNOSIS_OTHER" property="value"/></textarea>
        </td>
    </tr>
    <tr>
        <td class="admin"/>
        <td class="admin2" colspan="3">
            <INPUT class="button" type="button" name="save" id="save" onClick="doSubmit();" value="<%=getTran("Web.Occup","medwan.common.record",sWebLanguage)%>">
            <INPUT class="button" type="button" value="<%=getTran("Web","Back",sWebLanguage)%>" onclick="if (checkSaveButton('<%=sCONTEXTPATH%>','<%=getTran("Web.Occup","medwan.common.buttonquestion",sWebLanguage)%>')){window.location.href='<c:url value='/healthrecord/editTransaction.do'/>?be.mxs.healthrecord.createTransaction.transactionType=<bean:write name="transaction" scope="page" property="transactionType"/>&be.mxs.healthrecord.transaction_id=currentTransaction&ts=<%=getTs()%>'}">
        </td>
    </tr>
</table>
<script>
  function doSubmit(){
    document.transactionForm.save.disabled = true;
    document.transactionForm.submit();
  }
</script>
</form>
<%=writeJSButtons("transactionForm", "save")%>