<%@include file="/includes/validateUser.jsp"%>
<%@page errorPage="/includes/error.jsp"%>

<form name="transactionForm" method="POST" action='<c:url value="/healthrecord/updateTransaction.do"/>?ts=<%=getTs()%>' onclick="setSaveButton();" onkeyup="setSaveButton();">
    <bean:define id="transaction" name="be.mxs.webapp.wl.session.SessionContainerFactory.WO_SESSION_CONTAINER" property="currentTransactionVO"/>

    <input id="serverId" type="hidden" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.serverId" value="<bean:write name="transaction" scope="page" property="serverId"/>"/>
    <input id="transactionId" type="hidden" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.transactionId" value="<bean:write name="transaction" scope="page" property="transactionId"/>"/>

    <input type="hidden" name="subClass" value="NEURO"/>
    <input id="transactionType" type="hidden" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.transactionType" value="<bean:write name="transaction" scope="page" property="transactionType"/>"/>
    <input type="hidden" readonly name="be.mxs.healthrecord.updateTransaction.actionForwardKey" value="/healthrecord/editTransaction.do?be.mxs.healthrecord.createTransaction.transactionType=<bean:write name="transaction" scope="page" property="transactionType"/>&be.mxs.healthrecord.transaction_id=currentTransaction&ts=<%=getTs()%>"/>
    <input type="hidden" readonly name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_RAS" property="itemId"/>]>.value" value="medwan.common.false"/>

<script>
  function setTrue(itemType){
    var fieldName;
    fieldName = "currentTransactionVO.items.<ItemVO[hashCode="+itemType+"]>.value";
    document.all[fieldName].value = "medwan.common.true";
  }

  function setFalse(itemType){
    var fieldName;
    fieldName = "currentTransactionVO.items.<ItemVO[hashCode="+itemType+"]>.value";
    document.all[fieldName].value = "medwan.common.false";
  }
</script>

<table width="100%" class="list" cellspacing="0">
    <tr class="admin">
        <td><%=getTran("Web.Occup","medwan.healthrecord.neurologie",sWebLanguage)%></td>
        <td align="right" width="20%">
            <%=getLabel("Web.Occup","medwan.common.nothing-to-mention",sWebLanguage,"mcen-c0")%><input name="neuro-ras" type="checkbox" id="mcen-c0" value="medwan.common.true" onclick="if (this.checked == true) {hide('NEURO-details');setTrue('<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_RAS" property="itemId"/>'); } else {show('NEURO-details');setFalse('<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_RAS" property="itemId"/>'); }">
        </td>
        <td align="right" width ="1%"><a href="#top" class="topbutton">&nbsp;</a></td>
    </tr>
    <tr id="NEURO-details" style="display:none" width="100%">
        <td colspan="4" width="100%">
            <table width="100%" cellspacing="1">
                <tr class="admin">
                    <td colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.anamnese",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin" width="25%"><%=getTran("Web.Occup","medwan.healthrecord.neuro.force-loss-arm",sWebLanguage)%></td>
                    <td class="admin2" width="25%">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_ARM_RIGHT")%> type="checkbox" id="mcen-c1" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_ARM_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_ARM_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c1")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_ARM_LEFT")%> type="checkbox" id="mcen-c2" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_ARM_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_ARM_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c2")%>
                    </td>
                    <td class="admin" width="25%"><%=getTran("Web.Occup","medwan.healthrecord.neuro.force-loss-leg",sWebLanguage)%></td>
                    <td class="admin2" width="25%">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_LEG_RIGHT")%> type="checkbox" id="mcen-c3" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_LEG_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_LEG_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c3")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_LEG_LEFT")%> type="checkbox" id="mcen-c4" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_LEG_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_FORCE_LOSS_LEG_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c4")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.sensitivity-loss-arm",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_ARM_RIGHT")%> type="checkbox" id="mcen-c5" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_ARM_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_ARM_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c5")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_ARM_LEFT")%> type="checkbox" id="mcen-c6" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_ARM_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_ARM_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c6")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.sensitivity-loss-leg",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_LEG_RIGHT")%> type="checkbox" id="mcen-c7" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_LEG_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_LEG_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c7")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_LEG_LEFT")%> type="checkbox" id="mcen-c8" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_LEG_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_ANAMNESIS_SENSITIVITY_LOSS_LEG_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c8")%>
                    </td>
                </tr>
                <tr class="admin">
                    <td colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%></td>
                </tr>
                <tr  class="admin">
                    <td colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.clinical-examination.conscience",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination.conscience",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_CONSCIENCE")%> type="radio" onDblClick="uncheckRadio(this);" id="mcen-r1" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[GENERAL.CLINICAL_EXAMNIATION]ITEM_TYPE_CONSCIENCE" property="itemId"/>]>.value" value="medwan.common.normal" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_CONSCIENCE;value=medwan.common.normal" property="value" outputString="checked"/>><%=getLabel("Web.Occup","medwan.common.normal",sWebLanguage,"mcen-r1")%>
                    </td>
                    <td class="admin2" colspan="2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_CONSCIENCE")%> type="radio" onDblClick="uncheckRadio(this);" id="mcen-r2" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[GENERAL.CLINICAL_EXAMNIATION]ITEM_TYPE_CONSCIENCE" property="itemId"/>]>.value" value="medwan.common.anormal" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_CONSCIENCE;value=medwan.common.anormal" property="value" outputString="checked"/>><%=getLabel("Web.Occup","medwan.common.anormal",sWebLanguage,"mcen-r2")%>
                   </td>
                </tr>
                <tr class="admin">
                    <td colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.neuro.cranial-nerves",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.facialis-paresis",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FACIALIS_PARESIS_RIGHT")%> type="checkbox" id="mcen-c9" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FACIALIS_PARESIS_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FACIALIS_PARESIS_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c9")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FACIALIS_PARESIS_LEFT")%> type="checkbox" id="mcen-c10" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FACIALIS_PARESIS_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FACIALIS_PARESIS_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c10")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.facialis-contraction",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FACIALIS_CONTRACTION_RIGHT")%> type="checkbox" id="mcen-c11" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FACIALIS_CONTRACTION_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FACIALIS_CONTRACTION_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c11")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FACIALIS_CONTRACTION_LEFT")%> type="checkbox" id="mcen-c12" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FACIALIS_CONTRACTION_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FACIALIS_CONTRACTION_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c12")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.ptosis",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_PTOSIS_RIGHT")%> type="checkbox" id="mcen-c13" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_PTOSIS_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_PTOSIS_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c13")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_PTOSIS_LEFT")%> type="checkbox" id="mcen-c14" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_PTOSIS_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_PTOSIS_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c14")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.crion-deviation",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_CION_DEVIATION_RIGHT")%> type="checkbox" id="mcen-c15" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_CION_DEVIATION_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_CION_DEVIATION_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c15")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_CION_DEVIATION_LEFT")%> type="checkbox" id="mcen-c16" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_CION_DEVIATION_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_CION_DEVIATION_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c16")%>
                    </td>
                </tr>
                <tr class="admin">
                    <td colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.neuro.diminished-reflexes",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.knee-reflex",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_KNEE_REFLEX_RIGHT")%> type="checkbox" id="mcen-c17" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_KNEE_REFLEX_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_KNEE_REFLEX_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c17")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_KNEE_REFLEX_LEFT")%> type="checkbox" id="mcen-c18" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_KNEE_REFLEX_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_KNEE_REFLEX_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c18")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.hippocratic-chord-reflex",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HIPPOCRATIC_CORDA_REFLEX_RIGHT")%> type="checkbox" id="mcen-c19" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HIPPOCRATIC_CORDA_REFLEX_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HIPPOCRATIC_CORDA_REFLEX_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c19")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HIPPOCRATIC_CORDA_REFLEX_LEFT")%> type="checkbox" id="mcen-c20" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HIPPOCRATIC_CORDA_REFLEX_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HIPPOCRATIC_CORDA_REFLEX_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c20")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.babinsky",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_BABINSKY_RIGHT")%> type="checkbox" id="mcen-c21" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_BABINSKY_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_BABINSKY_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c21")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_BABINSKY_LEFT")%> type="checkbox" id="mcen-c22" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_BABINSKY_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_BABINSKY_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c22")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.biceps-reflex",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_BICEPS_REFLEX_RIGHT")%> type="checkbox" id="mcen-c23" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_BICEPS_REFLEX_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_BICEPS_REFLEX_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c23")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_BICEPS_REFLEX_LEFT")%> type="checkbox" id="mcen-c24" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_BICEPS_REFLEX_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_BICEPS_REFLEX_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c24")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.triceps-reflex",sWebLanguage)%></td>
                    <td class="admin2" colspan="3">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_TRICEPS_REFLEX_RIGHT")%> type="checkbox" id="mcen-c25" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_TRICEPS_REFLEX_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_TRICEPS_REFLEX_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c25")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_TRICEPS_REFLEX_LEFT")%> type="checkbox" id="mcen-c26" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_TRICEPS_REFLEX_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_TRICEPS_REFLEX_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c26")%>
                    </td>
                </tr>
                <tr class="admin">
                    <td colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.neuro.musscles",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.diminished-arm",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOW_MUSSCLE_ARM_RIGHT")%> type="checkbox" id="mcen-c27" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOW_MUSSCLE_ARM_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOW_MUSSCLE_ARM_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c27")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOW_MUSSCLE_ARM_LEFT")%> type="checkbox" id="mcen-c28" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOW_MUSSCLE_ARM_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOW_MUSSCLE_ARM_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c28")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.diminished-leg",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOW_MUSSCLE_LEG_RIGHT")%> type="checkbox" id="mcen-c29" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOW_MUSSCLE_LEG_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOW_MUSSCLE_LEG_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c29")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOW_MUSSCLE_LEG_LEFT")%> type="checkbox" id="mcen-c30" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOW_MUSSCLE_LEG_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOW_MUSSCLE_LEG_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c30")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.hypotonia-arm",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPOTONIA_ARM_RIGHT")%> type="checkbox" id="mcen-c31" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPOTONIA_ARM_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPOTONIA_ARM_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c31")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPOTONIA_ARM_LEFT")%> type="checkbox" id="mcen-c32" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPOTONIA_ARM_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPOTONIA_ARM_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c32")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.hypotonia-leg",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPOTONIA_LEG_RIGHT")%> type="checkbox" id="mcen-c33" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPOTONIA_LEG_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPOTONIA_LEG_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c33")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPOTONIA_LEG_LEFT")%> type="checkbox" id="mcen-c34" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPOTONIA_LEG_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPOTONIA_LEG_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c34")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.hypertonia-arm",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPERTONIA_ARM_RIGHT")%> type="checkbox" id="mcen-c35" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPERTONIA_ARM_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPERTONIA_ARM_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c35")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPERTONIA_ARM_LEFT")%> type="checkbox" id="mcen-c36" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPERTONIA_ARM_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPERTONIA_ARM_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c36")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.hypertonia-leg",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPERTONIA_LEG_RIGHT")%> type="checkbox" id="mcen-c37" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPERTONIA_LEG_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPERTONIA_LEG_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c37")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPERTONIA_LEG_LEFT")%> type="checkbox" id="mcen-c38" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPERTONIA_LEG_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_HYPERTONIA_LEG_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c38")%>
                    </td>
                </tr>
                <tr class="admin">
                    <td colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.neuro.sensitivity-disorders",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.arm",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_ARM_RIGHT")%> type="checkbox" id="mcen-c39" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_ARM_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_ARM_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c39")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_ARM_LEFTT")%> type="checkbox" id="mcen-c40" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_ARM_LEFTT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_ARM_LEFTT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c40")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.leg",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_LEG_RIGHT")%> type="checkbox" id="mcen-c41" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_LEG_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_LEG_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c41")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_LEG_LEFT")%> type="checkbox" id="mcen-c42" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_LEG_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_LOSS_SENSITIVITY_LEG_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c42")%>
                    </td>
                </tr>
                <tr class="admin">
                    <td colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.neuro.coordination-and-balance",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_ROMBERG")%> type="checkbox" id="mcen-c43" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_ROMBERG" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_ROMBERG;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.romberg",sWebLanguage,"mcen-c43")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_COMPULSARY_MOVEMENTS")%> type="checkbox" id="mcen-c44" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_COMPULSARY_MOVEMENTS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_COMPULSARY_MOVEMENTS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.compulsary-movements",sWebLanguage,"mcen-c44")%></td>
                    <td class="admin2" colspan="2"><input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_DISTURBED_MARCH_ON_LINE")%> type="checkbox" id="mcen-c45" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_DISTURBED_MARCH_ON_LINE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_DISTURBED_MARCH_ON_LINE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.disturbed-walk-on-line",sWebLanguage,"mcen-c45")%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.finger-nose",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FINGER_NOSE_TEST_RIGHT")%> type="checkbox" id="mcen-c46" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FINGER_NOSE_TEST_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FINGER_NOSE_TEST_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c46")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FINGER_NOSE_TEST_LEFT")%> type="checkbox" id="mcen-c47" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FINGER_NOSE_TEST_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_FINGER_NOSE_TEST_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c47")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.knee-heel",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_KNEE_HEEL_TEST_RIGHT")%> type="checkbox" id="mcen-c48" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_KNEE_HEEL_TEST_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_KNEE_HEEL_TEST_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c48")%>
                        <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_KNEE_HEEL_TEST_LEFT")%> type="checkbox" id="mcen-c49" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_KNEE_HEEL_TEST_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_KNEE_HEEL_TEST_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c49")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.neuro.unterberg",sWebLanguage)%></td>
                    <td class="admin2" colspan="3"><input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_UNTERBERG_RIGHT")%> type="checkbox" id="mcen-c50" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_UNTERBERG_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_UNTERBERG_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"mcen-c50")%>
                    <input <%=setRightClick("ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_UNTERBERG_LEFT")%> type="checkbox" id="mcen-c51" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_UNTERBERG_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_CLINICAL_EXAMINATION_UNTERBERG_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"mcen-c51")%></td>
                </tr>
                <tr class="admin">
                    <td colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_MS")%> type="checkbox" id="mcen-c52" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_MS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_MS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.ms",sWebLanguage,"mcen-c52")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_ALS")%> type="checkbox" id="mcen-c53" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_ALS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_ALS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.als",sWebLanguage,"mcen-c53")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_POLIO")%> type="checkbox" id="mcen-c54" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_POLIO" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_POLIO;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.polio",sWebLanguage,"mcen-c54")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_EPILEPSY")%> type="checkbox" id="mcen-c55" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_EPILEPSY" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_EPILEPSY;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.epilepsy",sWebLanguage,"mcen-c55")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_SPEECH_DISORDER")%> type="checkbox" id="mcen-c56" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_SPEECH_DISORDER" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_SPEECH_DISORDER;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.speech-disorders",sWebLanguage,"mcen-c56")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_SENSITIVITY_DISORDER")%> type="checkbox" id="mcen-c57" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_SENSITIVITY_DISORDER" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_SENSITIVITY_DISORDER;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.sensitivity-disorders",sWebLanguage,"mcen-c57")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_TREMOR")%> type="checkbox" id="mcen-c58" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_TREMOR" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_TREMOR;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.tremor",sWebLanguage,"mcen-c58")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_MUSCULAR_ATROFIA")%> type="checkbox" id="mcen-c59" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_MUSCULAR_ATROFIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_MUSCULAR_ATROFIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.musscle-atrophia",sWebLanguage,"mcen-c59")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_HEADACHE")%> type="checkbox" id="mcen-c60" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_HEADACHE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_HEADACHE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.headaches",sWebLanguage,"mcen-c60")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_TIA")%> type="checkbox" id="mcen-c61" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_TIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_TIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.tia",sWebLanguage,"mcen-c61")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_CVA")%> type="checkbox" id="mcen-c62" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_CVA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_CVA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.cva",sWebLanguage,"mcen-c62")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_PARKINSON")%> type="checkbox" id="mcen-c63" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_PARKINSON" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_PARKINSON;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.parkinson",sWebLanguage,"mcen-c63")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_NUERITIS_POLYNEURITIS")%> type="checkbox" id="mcen-c64" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_NUERITIS_POLYNEURITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_NUERITIS_POLYNEURITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.neuritis-polyneuritis",sWebLanguage,"mcen-c64")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_TRIGEMINI_NEURALGIA")%> type="checkbox" id="mcen-c65" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_TRIGEMINI_NEURALGIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_TRIGEMINI_NEURALGIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.trigeminus-neuralgia",sWebLanguage,"mcen-c65")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_MOTORIC_NEURONS_DISEASE")%> type="checkbox" id="mcen-c66" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_MOTORIC_NEURONS_DISEASE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_MOTORIC_NEURONS_DISEASE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.motoric-neurons-disease",sWebLanguage,"mcen-c66")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_MENTAL_RETARDATION")%> type="checkbox" id="mcen-c67" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_MENTAL_RETARDATION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_MENTAL_RETARDATION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.neuro.mental-retardation",sWebLanguage,"mcen-c67")%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.remark",sWebLanguage)%></td>
                    <td class="admin2" colspan="3">
                        <textarea onKeyup="resizeTextarea(this,10);limitChars(this,255);" <%=setRightClick("ITEM_TYPE_NEURO_DIAGNOSIS_OTHER")%> class="text" rows="2" cols="80" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_OTHER" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_NEURO_DIAGNOSIS_OTHER" property="value"/></textarea>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<%-- BUTTONS --%>
<%=ScreenHelper.alignButtonsStart()%>
    <INPUT class="button" type="button" name="save" onClick="doSubmit();" value="<%=getTran("Web.Occup","medwan.common.record",sWebLanguage)%>">
    <INPUT class="button" type="button" value="<%=getTran("Web","Back",sWebLanguage)%>" onclick="if (checkSaveButton('<%=sCONTEXTPATH%>','<%=getTran("Web.Occup","medwan.common.buttonquestion",sWebLanguage)%>')){window.location.href='<c:url value='/healthrecord/editTransaction.do'/>?be.mxs.healthrecord.createTransaction.transactionType=<bean:write name="transaction" scope="page" property="transactionType"/>&be.mxs.healthrecord.transaction_id=currentTransaction&ts=<%=getTs()%>'}">
    <%=writeResetButton("transactionForm",sWebLanguage)%>
<%=ScreenHelper.alignButtonsStop()%>

<script>
  function doSubmit(){
    document.transactionForm.save.disabled = true;
    <%
        SessionContainerWO sessionContainerWO = (SessionContainerWO)SessionContainerFactory.getInstance().getSessionContainerWO(request,SessionContainerWO.class.getName());
        out.print(takeOverTransaction(sessionContainerWO, activeUser,"document.transactionForm.submit();"));
    %>
  }

  document.all['neuro-ras'].onclick();
</script>

</form>
<%=writeJSButtons("transactionForm", "document.all['save']")%>