<%@page errorPage="/includes/error.jsp"%>
<%@include file="/includes/validateUser.jsp"%>
<%

%>
<form name="transactionForm" method="POST" action='<c:url value="/healthrecord/updateTransaction.do"/>?ts=<%=getTs()%>' onclick="setSaveButton();" onkeyup="setSaveButton();">
    <bean:define id="transaction" name="be.mxs.webapp.wl.session.SessionContainerFactory.WO_SESSION_CONTAINER" property="currentTransactionVO"/>

    <input type="hidden" id="transactionId" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.transactionId" value="<bean:write name="transaction" scope="page" property="transactionId"/>"/>
    <input type="hidden" id="transactionType" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.transactionType" value="<bean:write name="transaction" scope="page" property="transactionType"/>"/>
    <input type="hidden" id="serverId" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.serverId" value="<bean:write name="transaction" scope="page" property="serverId"/>"/>
    <input type="hidden" readonly name="be.mxs.healthrecord.updateTransaction.actionForwardKey" value="manageClinicalExamination.do?be.mxs.healthrecord.createTransaction.transactionType=<bean:write name="transaction" scope="page" property="transactionType"/>&be.mxs.healthrecord.transaction_id=currentTransaction"/>
    <input type="hidden" readonly name="subClass" value=".GASTRO"/>
    <input type="hidden" readonly name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CONTEXT_DEPARTMENT" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CONTEXT_DEPARTMENT" translate="false" property="value"/>"/>
    <input type="hidden" readonly name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CONTEXT_CONTEXT" translate="false" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CONTEXT_CONTEXT" translate="false" property="value"/>"/>

    <%
        if(session.getAttribute("sessionCounter")==null){
            session.setAttribute("sessionCounter",new Integer(0));
        }
        else{
            session.setAttribute("sessionCounter",new Integer(((Integer)session.getAttribute("sessionCounter")).intValue()+1));
        }

        session.setAttribute("sessionURL","/healthrecord/template.jsp?be.mxs.healthrecord.transaction_id=currentTransaction&Page="+customerInclude("/healthrecord/abdominaal.jsp")+"&message=true");
        if(request.getParameter("message") != null){
            out.print("<script>alert('"+getTran("Web.Occup","medwan.common.do-not-use-back",sWebLanguage)+"');</script>");
        }
    %>

    <script>
      function setTrue(itemType){
        var fieldName;
        fieldName = "currentTransactionVO.items.<ItemVO[hashCode="+itemType+"]>.value";
        document.getElementsByName(fieldName)[0].value = "medwan.common.true";
      }

      function setFalse(itemType){
        var fieldName;
        fieldName = "currentTransactionVO.items.<ItemVO[hashCode="+itemType+"]>.value";
        document.getElementsByName(fieldName)[0].value = "medwan.common.false";
      }
    </script>

    <br>

    <%-- gastro-enterologique --------------------------------------------------------------------%>
    <table border='0' width='100%' cellspacing="1" cellpadding="0" class="list">
        <%-- MAIN TITLE --%>
        <tr class="admin">
            <td colspan="2"><%=getTran("Web.Occup","medwan.healthrecord.anamnese.gastro-enterologique",sWebLanguage)%></td>
        </tr>

        <%-- DETAILS --%>
        <tr id="GASTRO-details">
            <td class="admin" width="25%">&nbsp;</td>
            <td class="admin2" width="*">
                <table width="100%">
                    <tr>
                        <td width="33%"><input <%=setRightClick("ITEM_TYPE_GASTRO_ANAMNESIS_ANOREXIA")%> type="checkbox" id="abdo-c1" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_ANOREXIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_ANOREXIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.anorexia",sWebLanguage,"abdo-c1")%></td>
                        <td width="33%"><input <%=setRightClick("ITEM_TYPE_GASTRO_ANAMNESIS_PYROSIS")%> type="checkbox" id="abdo-c2" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_PYROSIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_PYROSIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.dysphagia",sWebLanguage,"abdo-c2")%></td>
                        <td width="33%"><input <%=setRightClick("ITEM_TYPE_GASTRO_ANAMNESIS_NAUSEA")%> type="checkbox" id="abdo-c3" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_NAUSEA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_NAUSEA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.nausea",sWebLanguage,"abdo-c3")%></td>
                    </tr>
                    <tr>
                        <td><input <%=setRightClick("ITEM_TYPE_GASTRO_ANAMNESIS_VOMITING")%> type="checkbox" id="abdo-c4" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_VOMITING" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_VOMITING;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.vomiting",sWebLanguage,"abdo-c4")%></td>
                        <td><input <%=setRightClick("ITEM_TYPE_GASTRO_ANAMNESIS_CONSTIPATION")%> type="checkbox" id="abdo-c5" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_CONSTIPATION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_CONSTIPATION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.constipation",sWebLanguage,"abdo-c5")%></td>
                        <td><input <%=setRightClick("ITEM_TYPE_GASTRO_ANAMNESIS_DIARRHEA")%> type="checkbox" id="abdo-c6" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_DIARRHEA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_DIARRHEA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.diarrhea",sWebLanguage,"abdo-c6")%></td>
                    </tr>
                </table>
            </td>
        </tr>

        <tr id="medwan.healthrecord.gastro-details">
            <td colspan="2">
                <table width="100%" class="admin" cellspacing="1">
                    <%-- CLINICAL EXAMINATION ----------------------------------------------------%>
                    <tr>
                        <td class="clinical" colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%></td>
                    </tr>

                    <%-- INSPECTION --%>
                    <tr>
                        <td class="titleadmin" colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.gastro.inspection",sWebLanguage)%></td>
                    </tr>
                    <tr>
                        <td class="admin2" colspan="4"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_VERGETURES")%> type="checkbox" id="abdo-c7" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_VERGETURES" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_VERGETURES;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.vergetures",sWebLanguage,"abdo-c7")%></td>
                    </tr>

                    <%-- PALPATION --%>
                    <tr>
                        <td class="titleadmin" colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.gastro.palpation",sWebLanguage)%></td>
                    </tr>
                    <tr>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PALPATION_PAIN")%> type="checkbox" id="abdo-c8" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PALPATION_PAIN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PALPATION_PAIN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.palpation-pain",sWebLanguage,"abdo-c8")%></td>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_RELEASE_PAIN")%> type="checkbox" id="abdo-c9" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_RELEASE_PAIN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_RELEASE_PAIN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.release-pain",sWebLanguage,"abdo-c9")%></td>
                        <td class="admin2" colspan="2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_HERNIA_PORTS")%> type="checkbox" id="abdo-c10" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_HERNIA_PORTS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_HERNIA_PORTS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.hernia-ports",sWebLanguage,"abdo-c10")%></td>
                    </tr>
                    <tr>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MAC_BURNEY")%> type="checkbox" id="abdo-c11" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MAC_BURNEY" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MAC_BURNEY;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.mac-burnney",sWebLanguage,"abdo-c11")%></td>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_LIVER_BORDER_FELT")%> type="checkbox" id="abdo-c12" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_LIVER_BORDER_FELT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_LIVER_BORDER_FELT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.liverborder-felt",sWebLanguage,"abdo-c12")%></td>
                        <td class="admin2" colspan="2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MURPHY")%> type="checkbox" id="abdo-c13" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MURPHY" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MURPHY;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.murphy",sWebLanguage,"abdo-c13")%></td>
                    </tr>

                    <%-- PERCUSSION --%>
                    <tr>
                        <td class="titleadmin" colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.gastro.percussion",sWebLanguage)%></td>
                    </tr>
                    <tr>
                        <td class="admin2" colspan="4">
                            <input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PERCUSSION")%> type="text" class="text" size="90" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PERCUSSION" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PERCUSSION" property="value"/>" onblur="validateText(this);limitLength(this);">
                        </td>
                    </tr>

                    <%-- DIAGNOSE ----------------------------------------------------------------%>
                    <tr>
                        <td class="clinical" colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></td>
                    </tr>

                    <%-- TUMORS --%>
                    <tr>
                        <td class="titleadmin" colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.common.tumors",sWebLanguage)%></td>
                    </tr>
                    <tr>
                        <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_OESOPHAGE_BENIGN")%> type="checkbox" id="abdo-c14" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_OESOPHAGE_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_OESOPHAGE_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors.oesophagus",sWebLanguage,"abdo-c14")%></td>
                        <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_STOMACH_BENIGN")%> type="checkbox" id="abdo-c15" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_STOMACH_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_STOMACH_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors.stomach",sWebLanguage,"abdo-c15")%></td>
                        <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BOWEL_BENIGN")%> type="checkbox" id="abdo-c16" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BOWEL_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BOWEL_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors.bowel",sWebLanguage,"abdo-c16")%></td>
                        <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_COLON_BENIGN")%> type="checkbox" id="abdo-c17" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_COLON_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_COLON_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors.colon",sWebLanguage,"abdo-c17")%></td>
                    </tr>
                    <tr>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_RECTUM_BENIGN")%> type="checkbox" id="abdo-c18" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_RECTUM_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_RECTUM_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors.rectum",sWebLanguage,"abdo-c18")%></td>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_ANAL_BENIGN")%> type="checkbox" id="abdo-c19" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_ANAL_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_ANAL_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors.anal",sWebLanguage,"abdo-c19")%></td>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_BLADDER_BENIGN")%> type="checkbox" id="abdo-c20" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_BLADDER_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_BLADDER_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors.billiary-bladder",sWebLanguage,"abdo-c20")%></td>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_LIVER_BENIGN")%> type="checkbox" id="abdo-c21" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_LIVER_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_LIVER_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors.liver",sWebLanguage,"abdo-c21")%></td>
                    </tr>
                    <tr>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_DUCT_BENIGN")%> type="checkbox" id="abdo-c22" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_DUCT_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_DUCT_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors.billiary-ducts",sWebLanguage,"abdo-c22")%></td>
                        <td class="admin2" colspan="3"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BENIGN")%> type="checkbox" id="abdo-c23" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors",sWebLanguage,"abdo-c23")%></td>
                    </tr>

                    <%-- OTHER DISORDERS --%>
                    <tr>
                        <td class="titleadmin" colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.common.other",sWebLanguage)%></td>
                    </tr>

                    <%-- OTHER OESOPHAGAL --%>
                    <tr>
                        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.gastro.other-oesophagel-disorders",sWebLanguage)%></td>
                        <td class="admin2" colspan="3">
                            <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_OESOPHAGAL_PROBLEMS")%> type="text" class="text" size="90" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_OESOPHAGAL_PROBLEMS" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_OESOPHAGAL_PROBLEMS" property="value"/>" onblur="validateText(this);limitLength(this);">
                        </td>
                    </tr>
                    <tr>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_HERNIA_DIAPHRAGMATICA")%> type="checkbox" id="abdo-c24" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HERNIA_DIAPHRAGMATICA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HERNIA_DIAPHRAGMATICA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.hernia-diaphragmatica",sWebLanguage,"abdo-c24")%></td>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_GASTRITIS")%> type="checkbox" id="abdo-c26" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_GASTRITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_GASTRITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.gastritis",sWebLanguage,"abdo-c26")%></td>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_GASTRIC_ULCER")%> type="checkbox" id="abdo-c27" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_GASTRIC_ULCER" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_GASTRIC_ULCER;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.stomach-ulcer",sWebLanguage,"abdo-c27")%></td>
                        <td class="admin2">&nbsp;</td>
                    </tr>

                    <%-- OTHER STOMACH DISORDERS --%>
                    <tr>
                        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.gastro.other-stomach-disorders",sWebLanguage)%></td>
                        <td class="admin2" colspan="3"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_STOMACH_PROBLEM")%> type="text" class="text" size="90" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_STOMACH_PROBLEM" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_STOMACH_PROBLEM" property="value"/>" onblur="validateText(this);limitLength(this);"></td>
                    </tr>
                    <tr>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_DUODENUM_ULCER")%> type="checkbox" id="abdo-c28" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_DUODENUM_ULCER" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_DUODENUM_ULCER;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.duodenum-ulcer",sWebLanguage,"abdo-c28")%></td>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_CROHNS_DISEASE")%> type="checkbox" id="abdo-c29" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_CROHNS_DISEASE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_CROHNS_DISEASE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.crohns-disease",sWebLanguage,"abdo-c29")%></td>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_COLITIS_ULCEROSA")%> type="checkbox" id="abdo-c30" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_COLITIS_ULCEROSA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_COLITIS_ULCEROSA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.colitis-ulcerosa",sWebLanguage,"abdo-c30")%></td>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_CHRONIC_DIARRHEA")%> type="checkbox" id="abdo-c31" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_CHRONIC_DIARRHEA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_CHRONIC_DIARRHEA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.chronic-diarrhea",sWebLanguage,"abdo-c31")%></td>
                    </tr>
                    <tr>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_INGUINAL_HERNIA")%> type="checkbox" id="abdo-c32" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_INGUINAL_HERNIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_INGUINAL_HERNIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.inguinal-hernia",sWebLanguage,"abdo-c32")%></td>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_NAVEL_HERNIA")%> type="checkbox" id="abdo-c33" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_NAVEL_HERNIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_NAVEL_HERNIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.umbilical-hernia",sWebLanguage,"abdo-c33")%></td>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_BOWEL_POLYPS")%> type="checkbox" id="abdo-c34" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_BOWEL_POLYPS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_BOWEL_POLYPS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.bowel-polyps",sWebLanguage,"abdo-c34")%></td>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_IRRITABEL_BOWEL")%> type="checkbox" id="abdo-c35" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_IRRITABEL_BOWEL" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_IRRITABEL_BOWEL;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.irritable-bowel",sWebLanguage,"abdo-c35")%></td>
                    </tr>
                    <tr>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_HEMORRHOIDS")%> type="checkbox" id="abdo-c36" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HEMORRHOIDS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HEMORRHOIDS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.hemorrhoids",sWebLanguage,"abdo-c36")%></td>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_FISSURE")%> type="checkbox" id="abdo-c37" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_FISSURE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_FISSURE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.anal-fissura",sWebLanguage,"abdo-c37")%></td>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_ABCES")%> type="checkbox" id="abdo-c38" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_ABCES" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_ABCES;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.anal-abces",sWebLanguage,"abdo-c38")%></td>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_FISTULA")%> type="checkbox" id="abdo-c39" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_FISTULA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_FISTULA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.anal-fistula",sWebLanguage,"abdo-c39")%></td>
                    </tr>

                    <%-- OTHER BOWEL DISORDERS --%>
                    <tr>
                        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.gastro.other-bowel-disorders",sWebLanguage)%></td>
                        <td class="admin2" colspan="3"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_BOWEL")%> type="text" class="text" size="90" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_BOWEL" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_BOWEL" property="value"/>" onblur="validateText(this);limitLength(this);"></td>
                    </tr>
                    <tr>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_LIVER_STEATOSIS")%> type="checkbox" id="abdo-c40" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_LIVER_STEATOSIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_LIVER_STEATOSIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.liver-steatosis",sWebLanguage,"abdo-c40")%></td>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_LIVER_CIRRHOSIS")%> type="checkbox" id="abdo-c41" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_LIVER_CIRRHOSIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_LIVER_CIRRHOSIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.liver-cirrhosis",sWebLanguage,"abdo-c41")%></td>
                        <td class="admin2" colspan="2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_CHOLECYSTITIS")%> type="checkbox" id="abdo-c42" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_CHOLECYSTITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_CHOLECYSTITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.cholecystitis",sWebLanguage,"abdo-c42")%></td>
                    </tr>
                    <tr>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_HEPATITIS_A")%> type="checkbox" id="abdo-c43" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HEPATITIS_A" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HEPATITIS_A;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.hepatitis-a",sWebLanguage,"abdo-c43")%></td>
                        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_HEPATITIS_B")%> type="checkbox" id="abdo-c44" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HEPATITIS_B" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HEPATITIS_B;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.hepatitis-b",sWebLanguage,"abdo-c44")%></td>
                        <td class="admin2" colspan="2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_HEPATITIS_C")%> type="checkbox" id="abdo-c45" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HEPATITIS_C" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HEPATITIS_C;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.hepatitis-c",sWebLanguage,"abdo-c45")%></td>
                    </tr>

                    <%-- REMARK ------------------------------------------------------------------%>
                    <tr>
                        <td class="admin"><%=getTran("Web.Occup","medwan.common.remark",sWebLanguage)%></td>
                        <td class="admin2" colspan="3">
                            <textarea onKeyup="resizeTextarea(this,10);limitChars(this,255);" <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER")%> class="text" rows="2" cols="80" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER" property="value"/></textarea>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>

    <%-- BUTTONS --%>
    <%=ScreenHelper.alignButtonsStart()%>
        <INPUT class="button" type="button" name="save" onClick="doSubmit();" value="<%=getTran("Web.Occup","medwan.common.record",sWebLanguage)%>">
        <INPUT class="button" type="button" value="<%=getTran("Web","Back",sWebLanguage)%>" onclick="if (checkSaveButton('<%=sCONTEXTPATH%>','<%=getTran("Web.Occup","medwan.common.buttonquestion",sWebLanguage)%>')){window.location.href='<c:url value='/healthrecord/editTransaction.do'/>?be.mxs.healthrecord.createTransaction.transactionType=<bean:write name="transaction" scope="page" property="transactionType"/>&be.mxs.healthrecord.transaction_id=currentTransaction&ts=<%=getTs()%>'}">
        <%=writeResetButton("transactionForm",sWebLanguage)%>
    <%=ScreenHelper.alignButtonsStop()%>
</form>

<script>
  function doSubmit(){
    document.transactionForm.save.disabled = true;
    <%
        SessionContainerWO sessionContainerWO = (SessionContainerWO)SessionContainerFactory.getInstance().getSessionContainerWO(request,SessionContainerWO.class.getName());
        out.print(takeOverTransaction(sessionContainerWO, activeUser,"document.transactionForm.submit();"));
    %>
  }
</script>
<%=writeJSButtons("transactionForm", "document.getElementsByName('save')[0]")%>
