<%@page errorPage="/includes/error.jsp"%>
<%@include file="/includes/validateUser.jsp"%>
<%

%>
<bean:define id="transaction" name="be.mxs.webapp.wl.session.SessionContainerFactory.WO_SESSION_CONTAINER" property="currentTransactionVO"/>
<br>
<br>
<!--DERMATOLOGIE-->
<table border='0' width='100%' height='100%' cellspacing="1" cellpadding="0" class="list">
    <tr class="admin">
        <td colspan="2"><%=getTran("Web.Occup","medwan.healthrecord.anamnese.dermatologie",sWebLanguage)%></td>
    </tr>
    <tr id="dermato-details">
    <tr>
        <td class="admin" width="25%">&nbsp;</td>
        <td class="admin2" width="*">
            <table width="100%">
                <tr>
                    <td width="33%"><input <%=setRightClick("[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_ROUGEUR")%> type="checkbox" id="ce2-c1" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_ROUGEUR" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_ROUGEUR;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.rougeur",sWebLanguage,"ce2-c1")%></td>
                    <td width="33%"><input <%=setRightClick("[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_ICTERE")%> type="checkbox" id="ce2-c2" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_ICTERE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_ICTERE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.ictere",sWebLanguage,"ce2-c2")%></td>
                    <td width="33%"><input <%=setRightClick("[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_PRURIT")%> type="checkbox" id="ce2-c3" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_PRURIT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_PRURIT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.prurit",sWebLanguage,"ce2-c3")%></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.anamnese.other",sWebLanguage)%></td>
        <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_OTHER")%> type="text" class="text" size="80" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_OTHER" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_OTHER" property="value"/>" onblur="limitLength(this);"></td>
    </tr>
    <tr>
        <td class="title" colspan="2">
            <img src='<c:url value="/_img/pijl.gif"/>'>
            <a href="#" onclick="toggle_id('medwan.healthrecord.dermatologie-details');"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%> & <%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></a>
        </td>
    </tr>
    <tr id="medwan.healthrecord.dermatologie-details" style="display:none">
        <td colspan="2">
            <table width="100%" cellspacing="1" class="list">
                <tr>
                    <td class="titleadmin" colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_CICATRICE")%> type="checkbox" id="ce2-c4" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_CICATRICE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_CICATRICE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.cicatrice",sWebLanguage,"ce2-c4")%></td>
                    <td class="admin2" colspan="3"><input <%=setRightClick("[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_NAEVUS_SUSPECTE")%> type="checkbox" id="ce2-c5" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_NAEVUS_SUSPECTE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_NAEVUS_SUSPECTE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.naevus-suspecte",sWebLanguage,"ce2-c5")%></td>
                </tr>
                <tr>
                    <td class="titleadmin" colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2" width="25%"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_LIPOME")%> type="checkbox" id="ce2-c6" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_LIPOME" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_LIPOME;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.lipome",sWebLanguage,"ce2-c6")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_URTICAIRE")%> type="checkbox" id="ce2-c7" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_URTICAIRE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_URTICAIRE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.urticaire",sWebLanguage,"ce2-c7")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_DERMATITE")%> type="checkbox" id="ce2-c8" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_DERMATITE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_DERMATITE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.dermatite",sWebLanguage,"ce2-c8")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_VERRURES")%> type="checkbox" id="ce2-c9" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_VERRURES" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_VERRURES;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.verrues",sWebLanguage,"ce2-c9")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_ACNEE")%> type="checkbox" id="ce2-c10" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_ACNEE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_ACNEE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.acne",sWebLanguage,"ce2-c10")%></td>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_PSORIASIS")%> type="checkbox" id="ce2-c11" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_PSORIASIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_PSORIASIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.psoriasis",sWebLanguage,"ce2-c11")%></td>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_PITYRIASIS_VERSICOLOR")%> type="checkbox" id="ce2-c12" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_PITYRIASIS_VERSICOLOR" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_PITYRIASIS_VERSICOLOR;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.pityriasis-versicolor",sWebLanguage,"ce2-c12")%></td>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_ZONA")%> type="checkbox" id="ce2-c13" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_ZONA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_ZONA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.zona",sWebLanguage,"ce2-c13")%></td>
                </tr>

                <tr>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_AFFECTION_ONGLES")%> type="checkbox" id="ce2-c14" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_AFFECTION_ONGLES" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_AFFECTION_ONGLES;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.affection-ongles",sWebLanguage,"ce2-c14")%></td>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_MYCOSES")%> type="checkbox" id="ce2-c15" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_MYCOSES" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_MYCOSES;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.mycoses",sWebLanguage,"ce2-c15")%></td>
                    <td class="admin2" colspan="2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_SEBUMCYSTE")%> type="checkbox" id="ce2-c16" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_SEBUMCYSTE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_SEBUMCYSTE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.sebumcyste",sWebLanguage,"ce2-c16")%></td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<br>
<br>

<!--ORL-->
<table border='0' width='100%' height='100%' cellspacing="1" cellpadding="0" class="list">
    <tr class="admin">
        <td colspan="2"><%=getTran("Web.Occup","medwan.healthrecord.ORL",sWebLanguage)%></td>
    </tr>
    <tr id="ORL-details">
        <td class="admin" width="25%">&nbsp;</td>
        <td class="admin2" width="*">
            <table width="100%">
                <tr>
                    <td width="33%"><input <%=setRightClick("ITEM_TYPE_ORL_ANAMNESIS_OTITIS")%> type="checkbox" id="ce2-c17" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_OTITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_OTITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.otite",sWebLanguage,"ce2-c17")%></td>
                    <td width="33%"><input <%=setRightClick("ITEM_TYPE_ORL_ANAMNESIS_ACOUPHENE")%> type="checkbox" id="ce2-c18" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_ACOUPHENE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_ACOUPHENE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.acouphene",sWebLanguage,"ce2-c18")%></td>
                    <td width="33%"><input <%=setRightClick("ITEM_TYPE_ORL_ANAMNESIS_AUDITIVE_LOSS")%> type="checkbox" id="ce2-c19" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_AUDITIVE_LOSS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_AUDITIVE_LOSS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.perte-auditive",sWebLanguage,"ce2-c19")%></td>
                </tr>
                <tr>
                    <td><input <%=setRightClick("ITEM_TYPE_ORL_ANAMNESIS_EQUILIBRE_DISORDER")%> type="checkbox" id="ce2-c20" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_EQUILIBRE_DISORDER" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_EQUILIBRE_DISORDER;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.trouble-equilibre",sWebLanguage,"ce2-c20")%></td>
                    <td><input <%=setRightClick("ITEM_TYPE_ORL_ANAMNESIS_NASAL_THROWING")%> type="checkbox" id="ce2-c21" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_NASAL_THROWING" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_NASAL_THROWING;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.jetage-nasal",sWebLanguage,"ce2-c21")%></td>
                    <td><input <%=setRightClick("ITEM_TYPE_ORL_ANAMNESIS_VERTIGO")%> type="checkbox" id="ce2-c22" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_VERTIGO" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_VERTIGO;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.vertigo",sWebLanguage,"ce2-c22")%></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td class="title" colspan="2">
            <img src='<c:url value="/_img/pijl.gif"/>'>
            <a href="#" onclick="toggle_id('medwan.healthrecord.orl-details');"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%> & <%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></a>
        </td>
    </tr>
    <tr id="medwan.healthrecord.orl-details" style="display:none">
        <td colspan="2">
            <table width="100%" cellspacing="1" class="list">
                <tr>
                    <td class="titleadmin" colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin" width="25%"><%=getTran("Web.Occup","medwan.healthrecord.ORL.ganglions-lymphatiques",sWebLanguage)%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_ORL_CLINICAL_EXAMINATION_LYMPHATIC_GANGLIA_SUBMAXILLARY")%> type="checkbox" id="ce2-c23" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_CLINICAL_EXAMINATION_LYMPHATIC_GANGLIA_SUBMAXILLARY" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_CLINICAL_EXAMINATION_LYMPHATIC_GANGLIA_SUBMAXILLARY;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.ganglions-lymphatiques.sous-maxillaires",sWebLanguage,"ce2-c23")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_ORL_CLINICAL_EXAMINATION_LYMPHATIC_GANGLIA_NECK")%> type="checkbox" id="ce2-c24" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_CLINICAL_EXAMINATION_LYMPHATIC_GANGLIA_NECK" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_CLINICAL_EXAMINATION_LYMPHATIC_GANGLIA_NECK;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.ganglions-lymphatiques.cou",sWebLanguage,"ce2-c24")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_ORL_CLINICAL_EXAMINATION_LYMPHATIC_RETRO_AURICULAR")%> type="checkbox" id="ce2-c25" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_CLINICAL_EXAMINATION_LYMPHATIC_RETRO_AURICULAR" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_CLINICAL_EXAMINATION_LYMPHATIC_RETRO_AURICULAR;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.ganglions-lymphatiques.retro-auriculaires",sWebLanguage,"ce2-c25")%></td>
                </tr>
                <tr>
                    <td class="titleadmin" colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.ORL.otite-externe",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_EXTERNA_RIGHT")%> type="checkbox" id="ce2-c26" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_EXTERNA_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_EXTERNA_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"ce2-c26")%>
                        <input type="checkbox" id="ce2-c27" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_EXTERNA_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_EXTERNA_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"ce2-c27")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.ORL.otite-interne",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_INTERNA_RIGHT")%> type="checkbox" id="ce2-c28" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_INTERNA_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_INTERNA_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"ce2-c28")%>
                        <input type="checkbox" id="ce2-c29" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_INTERNA_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_INTERNA_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"ce2-c29")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.ORL.tympan-perfore",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_TYMPAN_PERFORATION_RIGHT")%> type="checkbox" id="ce2-c30" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_TYMPAN_PERFORATION_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_TYMPAN_PERFORATION_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"ce2-c30")%>
                        <input type="checkbox" id="ce2-c31" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_TYMPAN_PERFORATION_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_TYMPAN_PERFORATION_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"ce2-c31")%>
                   </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.ORL.bouchon-de-cerumen",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_CERUMEN_RIGHT")%> type="checkbox" id="ce2-c32" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_CERUMEN_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_CERUMEN_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"ce2-c32")%>
                        <input type="checkbox" id="ce2-c33" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_CERUMEN_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_CERUMEN_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"ce2-c33")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.ORL.surdite-professionnelle",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_PROFESSIONAL_DEAFNESS_RIGHT")%> type="checkbox" id="ce2-c34" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_PROFESSIONAL_DEAFNESS_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_PROFESSIONAL_DEAFNESS_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"ce2-c34")%>
                        <input type="checkbox" id="ce2-c35" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_PROFESSIONAL_DEAFNESS_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_PROFESSIONAL_DEAFNESS_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"ce2-c35")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.ORL.hypoacousie",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_HYPOACCUSY_RIGHT")%> type="checkbox" id="ce2-c36" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_HYPOACCUSY_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_HYPOACCUSY_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"ce2-c36")%>
                        <input type="checkbox" id="ce2-c37" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_HYPOACCUSY_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_HYPOACCUSY_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"ce2-c37")%>
                    </td>
                </tr>
                <tr><td>&nbsp;</td></tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_SINUSITIS")%> type="checkbox" id="ce2-c38" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_SINUSITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_SINUSITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.sinusite",sWebLanguage,"ce2-c38")%></td>
                    <td class="admin2" colspan="3"><input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_RHINITIS")%> type="checkbox" id="ce2-c39" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_RHINITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_RHINITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.rhinite",sWebLanguage,"ce2-c39")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_PHARYNGITIS")%> type="checkbox" id="ce2-c40" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_PHARYNGITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_PHARYNGITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.pharyngite",sWebLanguage,"ce2-c40")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_ADENOID_VEGETATIONS")%> type="checkbox" id="ce2-c41" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_ADENOID_VEGETATIONS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_ADENOID_VEGETATIONS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.hypertrophie-des-amygdales",sWebLanguage,"ce2-c41")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_NASAL_SEPTUM_DEVIATION")%> type="checkbox" id="ce2-c42" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_NASAL_SEPTUM_DEVIATION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_NASAL_SEPTUM_DEVIATION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.deviation-cloison-nasale",sWebLanguage,"ce2-c42")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_DENTAL_CARE_NEEDED")%> type="checkbox" id="ce2-c43" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_DENTAL_CARE_NEEDED" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_DENTAL_CARE_NEEDED;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.dents-a-soigner",sWebLanguage,"ce2-c43")%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.remark",sWebLanguage)%></td>
                    <td class="admin2" colspan="3">
                        <textarea onKeyup="resizeTextarea(this,10);limitChars(this,255);" <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_OTHER")%> class="text" rows="2" cols="80" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_OTHER" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_OTHER" property="value"/></textarea>
                    </td>
                </tr>
           </table>
        </td>
    </tr>
</table>

<br>
<br>

<!--VISUS-->
<table border='0' width='100%' height='100%' cellspacing="1" cellpadding="0" class="list">
    <tr class="admin">
        <td colspan="2"><%=getTran("Web.Occup","medwan.healthrecord.vision",sWebLanguage)%></td>
    </tr>
    <tr>
        <td class="admin" width="25%">&nbsp;</td>
        <td class="admin2" width="*">
            <table width="100%">
                <tr>
                    <td width="25%"><input <%=setRightClick("ITEM_TYPE_VISUS_ANAMNESIS_RUNNING_EYE")%> type="checkbox" id="ce2-c44" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_ANAMNESIS_RUNNING_EYE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_ANAMNESIS_RUNNING_EYE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.vision.ecoulement-oeuil",sWebLanguage,"ce2-c44")%></td>
                    <td width="25%"><input <%=setRightClick("ITEM_TYPE_VISUS_ANAMNESIS_STRANGE_CORPUS")%> type="checkbox" id="ce2-c45" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_ANAMNESIS_STRANGE_CORPUS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_ANAMNESIS_STRANGE_CORPUS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.vision.corps-etranger",sWebLanguage,"ce2-c45")%></td>
                    <td width="25%"><input <%=setRightClick("ITEM_TYPE_VISUS_ANAMNESIS_GLASSES")%> type="checkbox" id="ce2-c46" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_ANAMNESIS_GLASSES" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_ANAMNESIS_GLASSES;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ophtalmology.acuite-visuelle.lunettes",sWebLanguage,"ce2-c46")%></td>
                    <td width="25%"><input <%=setRightClick("ITEM_TYPE_VISUS_ANAMNESIS_LENSES")%> type="checkbox" id="ce2-c47" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_ANAMNESIS_LENSES" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_ANAMNESIS_LENSES;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ophtalmology.acuite-visuelle.verres-de-contact",sWebLanguage,"ce2-c47")%></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td class="title" colspan="2">
            <img src='<c:url value="/_img/pijl.gif"/>'>
            <a href="#" onclick="toggle_id('medwan.healthrecord.visus-details');"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%> & <%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></a>
        </td>
    </tr>
    <tr id="medwan.healthrecord.visus-details" style="display:none">
        <td colspan="2">
            <table width="100%" cellspacing="1" class="list">
                <tr>
                    <td class="titleadmin" colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin" width="25%"><%=getTran("Web.Occup","medwan.healthrecord.vision.acuite-visuelle-insuffisante-de-loin",sWebLanguage)%></td>
                    <td class="admin2" width="25%">
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_INSUFFICIENT_SHARP_FAR_RIGHT")%> type="checkbox" id="ce2-c48" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_INSUFFICIENT_SHARP_FAR_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_INSUFFICIENT_SHARP_FAR_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"ce2-c48")%>
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_INSUFFICIENT_SHARP_FAR_LEFT")%> type="checkbox" id="ce2-c49" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_INSUFFICIENT_SHARP_FAR_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_INSUFFICIENT_SHARP_FAR_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"ce2-c49")%>
                    </td>
                    <td class="admin" width="25%"><%=getTran("Web.Occup","medwan.healthrecord.vision.acuite-visuelle-insuffisante-proche",sWebLanguage)%></td>
                    <td class="admin2" width="25%">
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_INSUFFICIENT_SHARP_NEAR_RIGHT")%> type="checkbox" id="ce2-c50" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_INSUFFICIENT_SHARP_NEAR_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_INSUFFICIENT_SHARP_NEAR_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"ce2-c50")%>
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_INSUFFICIENT_SHARP_NEAR_LEFT")%> type="checkbox" id="ce2-c51" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_INSUFFICIENT_SHARP_NEAR_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_INSUFFICIENT_SHARP_NEAR_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"ce2-c51")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.vision.amblyopie",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_AMBLYOPIA_RIGHT")%> type="checkbox" id="ce2-c52" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_AMBLYOPIA_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_AMBLYOPIA_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"ce2-c52")%>
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_AMBLYOPIA_LEFT")%> type="checkbox" id="ce2-c53" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_AMBLYOPIA_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_AMBLYOPIA_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"ce2-c53")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.vision.erreur-champs-vision",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_ERROR_VISUS_AREA_RIGHT")%> type="checkbox" id="ce2-c54" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_ERROR_VISUS_AREA_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_ERROR_VISUS_AREA_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"ce2-c54")%>
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_ERROR_VISUS_AREA_LEFT")%> type="checkbox" id="ce2-c55" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_ERROR_VISUS_AREA_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_ERROR_VISUS_AREA_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"ce2-c55")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.vision.cataracte",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_CATARACT_RIGHT")%> type="checkbox" id="ce2-c56" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_CATARACT_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_CATARACT_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"ce2-c56")%>
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_CATARACT_LEFT")%> type="checkbox" id="ce2-c57" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_CATARACT_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_CATARACT_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"ce2-c57")%>
                    </td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_HYPERMETROPIA")%> type="checkbox" id="ce2-c58" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_HYPERMETROPIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_HYPERMETROPIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.vision.hypermetropia",sWebLanguage,"ce2-c58")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_ASTIGMATISM")%> type="checkbox" id="ce2-c59" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_ASTIGMATISM" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_ASTIGMATISM;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.vision.astigmatism",sWebLanguage,"ce2-c59")%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.vision.borgne",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_ONE_EYED_RIGHT")%> type="checkbox" id="ce2-c60" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_ONE_EYED_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_ONE_EYED_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"ce2-c60")%>
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_ONE_EYED_LEFT")%> type="checkbox" id="ce2-c61" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_ONE_EYED_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_ONE_EYED_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"ce2-c61")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.vision.decollement-retine",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_RETINA_LEFT_RIGHT")%> type="checkbox" id="ce2-c62" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_RETINA_LEFT_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_RETINA_LEFT_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"ce2-c62")%>
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_RETINA_LEFT_LEFT")%> type="checkbox" id="ce2-c63" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_RETINA_LEFT_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_RETINA_LEFT_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"ce2-c63")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.vision.glaucome",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_GLAUCOMA_RIGHT")%> type="checkbox" id="ce2-c64" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_GLAUCOMA_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_GLAUCOMA_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"ce2-c64")%>
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_GLAUCOMA_LEFT")%> type="checkbox" id="ce2-c65" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_GLAUCOMA_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_GLAUCOMA_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"ce2-c65")%>
                    </td>
                    <td class="admin2" colspan="2"><input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_STRABISMUS")%> type="checkbox" id="ce2-c66" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_STRABISMUS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_STRABISMUS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.vision.strabisme",sWebLanguage,"ce2-c66")%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.vision.conjonctivite",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_CONJUNCTIVITIS_RIGHT")%> type="checkbox" id="ce2-c67" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_CONJUNCTIVITIS_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_CONJUNCTIVITIS_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"ce2-c67")%>
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_CONJUNCTIVITIS_LEFT")%> type="checkbox" id="ce2-c68" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_CONJUNCTIVITIS_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_CONJUNCTIVITIS_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"ce2-c68")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.vision.conjonctivite-allergique",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_ALLERGIC_CONJUNCTIVITIS_RIGHT")%> type="checkbox" id="ce2-c69" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_ALLERGIC_CONJUNCTIVITIS_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_ALLERGIC_CONJUNCTIVITIS_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"ce2-c69")%>
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_ALLERGIC_CONJUNCTIVITIS_LEFT")%> type="checkbox" id="ce2-c70" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_ALLERGIC_CONJUNCTIVITIS_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_ALLERGIC_CONJUNCTIVITIS_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"ce2-c70")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.vision.lesion-oeuil",sWebLanguage)%></td>
                    <td class="admin2" colspan="3">
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_EYE_LAESION_RIGHT")%> type="checkbox" id="ce2-c71" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_EYE_LAESION_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_EYE_LAESION_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"ce2-c71")%>
                        <input <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_EYE_LAESION_LEFT")%> type="checkbox" id="ce2-c72" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_EYE_LAESION_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_EYE_LAESION_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"ce2-c72")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.remark",sWebLanguage)%></td>
                    <td class="admin2" colspan="3">
                        <textarea onKeyup="resizeTextarea(this,10);limitChars(this,255);" <%=setRightClick("ITEM_TYPE_VISUS_DIAGNOSIS_OTHER")%> class="text" rows="2" cols="80" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_OTHER" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VISUS_DIAGNOSIS_OTHER" property="value"/></textarea>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<br>
<br>

<!--CARDIAL-->
<table border='0' width='100%' height='100%' cellspacing="1" cellpadding="0" class="list">
    <tr class="admin">
        <td colspan="2"><%=getTran("Web.Occup","medwan.healthrecord.cardial",sWebLanguage)%></td>
    </tr>
    <tr id="CARDIAL-details" width="100%">
        <td class="admin" width="25%">&nbsp;</td>
        <td class="admin2" width="*">
            <table width="100%">
                <tr>
                    <td width="25%"><input <%=setRightClick("ITEM_TYPE_CARDIAL_ANAMNESIS_EFFORT_DYSPNOE")%> type="checkbox" id="ce2-c73" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_ANAMNESIS_EFFORT_DYSPNOE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_ANAMNESIS_EFFORT_DYSPNOE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.cardial.dyspnee-effort",sWebLanguage,"ce2-c73")%></td>
                    <td width="25%"><input <%=setRightClick("ITEM_TYPE_CARDIAL_ANAMNESIS_HYPERTENSION")%> type="checkbox" id="ce2-c74" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_ANAMNESIS_HYPERTENSION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_ANAMNESIS_HYPERTENSION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.cardial.hypertension",sWebLanguage,"ce2-c74")%></td>
                    <td width="25%"><input <%=setRightClick("ITEM_TYPE_CARDIAL_ANAMNESIS_PALPITATIONS")%> type="checkbox" id="ce2-c75" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_ANAMNESIS_PALPITATIONS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_ANAMNESIS_PALPITATIONS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.cardial.palpitations",sWebLanguage,"ce2-c75")%></td>
                    <td width="25%"><input <%=setRightClick("ITEM_TYPE_CARDIAL_ANAMNESIS_PRECORDIALGIA")%> type="checkbox" id="ce2-c76" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_ANAMNESIS_PRECORDIALGIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_ANAMNESIS_PRECORDIALGIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.cardial.precordialgie",sWebLanguage,"ce2-c76")%></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td class="title" colspan="2">
            <img src='<c:url value="/_img/pijl.gif"/>'>
            <a href="#" onclick="toggle_id('medwan.healthrecord.cardial-details');"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%> & <%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></a>
        </td>
    </tr>
    <tr id="medwan.healthrecord.cardial-details" style="display:none">
        <td colspan="2">
            <table width="100%" cellspacing="1" class="list">
                <tr>
                    <td class=titleadmin colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.cardial.auscultation",sWebLanguage)%></td>
                    <td class="admin2" colspan="3">
                        <textarea onKeyup="resizeTextarea(this,10);limitChars(this,255);" <%=setRightClick("ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_AUSCULTATION")%> class="text" rows="2" cols="60" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_AUSCULTATION" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_AUSCULTATION" property="value"/></textarea>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.cardial.frequence-cardiaque",sWebLanguage)%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_HEARTH_FREQUENCY")%> type="text" class="text" size="3" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_HEARTH_FREQUENCY" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_HEARTH_FREQUENCY" property="value"/>">/min</td>
                    <td class="admin2" colspan="2">
                        <input <%=setRightClick("ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_HEARTH_RYTMH")%> type="radio" onDblClick="uncheckRadio(this);" id="ce2-r1" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_HEARTH_RYTMH" property="itemId"/>]>.value" value="medwan.healthrecord.cardial.regulier" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_HEARTH_RYTMH;value=medwan.healthrecord.cardial.regulier" property="value" outputString="checked"/>><%=getLabel("Web.Occup","medwan.healthrecord.cardial.regulier",sWebLanguage,"ce2-r1")%>
                        <input <%=setRightClick("ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_HEARTH_RYTMH")%> type="radio" onDblClick="uncheckRadio(this);" id="ce2-r2" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_HEARTH_RYTMH" property="itemId"/>]>.value" value="medwan.healthrecord.cardial.irregulier" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_HEARTH_RYTMH;value=medwan.healthrecord.cardial.irregulier" property="value" outputString="checked"/>><%=getLabel("Web.Occup","medwan.healthrecord.cardial.irregulier",sWebLanguage,"ce2-r2")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.cardial.pression-arterielle",sWebLanguage)%></td>
                    <td class="admin2"><%=getTran("Web.Occup","medwan.healthrecord.cardial.bras-droit",sWebLanguage)%>
                        <input <%=setRightClick("ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_SYSTOLIC_PRESSURE_RIGHT")%> type="text" class="text" size="3" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_SYSTOLIC_PRESSURE_RIGHT" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_SYSTOLIC_PRESSURE_RIGHT" property="value"/>">/<input <%=setRightClick("ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_DIASTOLIC_PRESSURE_RIGHT")%> type="text" class="text" size="3" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_DIASTOLIC_PRESSURE_RIGHT" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_DIASTOLIC_PRESSURE_RIGHT" property="value"/>">mmHg
                    </td>
                    <td class="admin2" colspan="2"><%=getTran("Web.Occup","medwan.healthrecord.cardial.bras-gauche",sWebLanguage)%>
                        <input <%=setRightClick("ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_SYSTOLIC_PRESSURE_LEFT")%> type="text" class="text" size="3" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_SYSTOLIC_PRESSURE_LEFT" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_SYSTOLIC_PRESSURE_LEFT" property="value"/>">/<input <%=setRightClick("ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_DIASTOLIC_PRESSURE_LEFT")%> type="text" class="text" size="3" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_DIASTOLIC_PRESSURE_LEFT" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_CLINICAL_EXAMINATION_DIASTOLIC_PRESSURE_LEFT" property="value"/>">mmHg
                    </td>
                </tr>
                <tr>
                    <td class=titleadmin colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_CARDIAL_DIAGNOSIS_ANGINA_PECTORIS")%> type="checkbox" id="ce2-c77" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_DIAGNOSIS_ANGINA_PECTORIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_DIAGNOSIS_ANGINA_PECTORIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.cardial.angine-de-poitrine",sWebLanguage,"ce2-c77")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_CARDIAL_DIAGNOSIS_AMI")%> type="checkbox" id="ce2-c78" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_DIAGNOSIS_AMI" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_DIAGNOSIS_AMI;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.cardial.infarctus-aigu-myocarde",sWebLanguage,"ce2-c78")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_CARDIAL_DIAGNOSIS_CENTRAL_ANEURYSMA")%> type="checkbox" id="ce2-c79" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_DIAGNOSIS_CENTRAL_ANEURYSMA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_DIAGNOSIS_CENTRAL_ANEURYSMA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.cardial.anevrysme",sWebLanguage,"ce2-c79")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_CARDIAL_DIAGNOSIS_PACEMAKER")%> type="checkbox" id="ce2-c80" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_DIAGNOSIS_PACEMAKER" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_DIAGNOSIS_PACEMAKER;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.cardial.pacemaker",sWebLanguage,"ce2-c80")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_CARDIAL_DIAGNOSIS_HYPOTENSION")%> type="checkbox" id="ce2-c81" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_DIAGNOSIS_HYPOTENSION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_DIAGNOSIS_HYPOTENSION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.cardial.hypotension",sWebLanguage,"ce2-c81")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_CARDIAL_DIAGNOSIS_CARDIOMYOPATHIA")%> type="checkbox" id="ce2-c82" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_DIAGNOSIS_CARDIOMYOPATHIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_DIAGNOSIS_CARDIOMYOPATHIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.cardial.cardiomyopathie",sWebLanguage,"ce2-c82")%></td>
                    <td class="admin2" colspan="2"><input <%=setRightClick("ITEM_TYPE_CARDIAL_DIAGNOSIS_HYPERTENSION")%> type="checkbox" id="ce2-c83" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_DIAGNOSIS_HYPERTENSION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_DIAGNOSIS_HYPERTENSION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.cardial.hypertension",sWebLanguage,"ce2-c83")%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.remark",sWebLanguage)%></td>
                    <td class="admin2"colspan="3">
                        <textarea onKeyup="resizeTextarea(this,10);limitChars(this,255);" <%=setRightClick("ITEM_TYPE_CARDIAL_DIAGNOSIS_OTHER")%> class="text" rows="2" cols="80" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_DIAGNOSIS_OTHER" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CARDIAL_DIAGNOSIS_OTHER" property="value"/></textarea>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>