<%@page errorPage="/includes/error.jsp"%>
<%@include file="/includes/validateUser.jsp"%>

<bean:define id="transaction" name="be.mxs.webapp.wl.session.SessionContainerFactory.WO_SESSION_CONTAINER" property="currentTransactionVO"/>

<%-- VASCULAR ------------------------------------------------------------------------------------%>
<br><br>
<table border='0' width='100%' height='100%' cellspacing="1" cellpadding="0" class="list">
    <tr class="admin">
        <td colspan="2"><%=getTran("Web.Occup","medwan.healthrecord.anamnese.vasculaire",sWebLanguage)%></td>
    </tr>
    <tr id="VASCULAR-details">
        <td class="admin" width="25%">&nbsp;</td>
        <td class="admin2" width="*">
            <table width="100%">
                <tr>
                    <td width="50%"><input <%=setRightClick("ITEM_TYPE_VASCULAR_ANAMNESIS_HEAVYLEGGS")%> type="checkbox" id="ce3-c1" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_ANAMNESIS_HEAVYLEGGS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_ANAMNESIS_HEAVYLEGGS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.vascular.heavyleggs",sWebLanguage,"ce3-c1")%></td>
                    <td width="50%"><input <%=setRightClick("ITEM_TYPE_VASCULAR_ANAMNESIS_PAIN_WHEN_WALKING")%> type="checkbox" id="ce3-c2" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_ANAMNESIS_PAIN_WHEN_WALKING" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_ANAMNESIS_PAIN_WHEN_WALKING;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.vascular.pain-when-walking",sWebLanguage,"ce3-c2")%></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td class="title" colspan="2">
            <img src='<c:url value="/_img/themes/default/pijl.gif"/>'>
            <a href="#" onclick="toggle_id('medwan.healthrecord.vascular-details');"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%> & <%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></a>
        </td>
    </tr>
    <tr id="medwan.healthrecord.vascular-details" style="display:none">
        <td colspan="2">
            <table width="100%" cellspacing="1" class="1">
                <tr>
                    <td class="titleadmin" colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_VASCULAR_CLINICAL_EXAMINATION_HEMANGIOMES")%> type="checkbox" id="ce3-c3" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_CLINICAL_EXAMINATION_HEMANGIOMES" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_CLINICAL_EXAMINATION_HEMANGIOMES;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.vascular.hemangiomes",sWebLanguage,"ce3-c3")%></td>
                    <td class="admin" width="25%"><%=getTran("Web.Occup","medwan.healthrecord.vascular.varices",sWebLanguage)%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_VASCULAR_CLINICAL_EXAMINATION_VARICES_RIGHT")%> type="checkbox" id="ce3-c4" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_CLINICAL_EXAMINATION_VARICES_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_CLINICAL_EXAMINATION_VARICES_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"ce3-c4")%>
                        <input <%=setRightClick("ITEM_TYPE_VASCULAR_CLINICAL_EXAMINATION_VARICES_LEFT")%> type="checkbox" id="ce3-c5" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_CLINICAL_EXAMINATION_VARICES_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_CLINICAL_EXAMINATION_VARICES_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"ce3-c5")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_VASCULAR_CLINICAL_EXAMINATION_OEDEMA_LEGS")%> type="checkbox" id="ce3-c6" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_CLINICAL_EXAMINATION_OEDEMA_LEGS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_CLINICAL_EXAMINATION_OEDEMA_LEGS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.vascular.oedema-legs",sWebLanguage,"ce3-c6")%></td>
                </tr>
                <tr>
                    <td class="admin2" colspan="4"><input <%=setRightClick("ITEM_TYPE_VASCULAR_CLINICAL_EXAMINATION_VENOUS_ULCERS")%> type="checkbox" id="ce3-c7" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_CLINICAL_EXAMINATION_VENOUS_ULCERS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_CLINICAL_EXAMINATION_VENOUS_ULCERS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.vascular.venous-ulcers",sWebLanguage,"ce3-c7")%></td>
                </tr>
                <tr>
                    <td class="titleadmin" colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_VASCULAR_DIAGNOSIS_CLAUDICATIO")%> type="checkbox" id="ce3-c8" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_DIAGNOSIS_CLAUDICATIO" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_DIAGNOSIS_CLAUDICATIO;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.vascular.claudicatio",sWebLanguage,"ce3-c8")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_VASCULAR_DIAGNOSIS_ARTERIOSCLEROSIS")%> type="checkbox" id="ce3-c9" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_DIAGNOSIS_ARTERIOSCLEROSIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_DIAGNOSIS_ARTERIOSCLEROSIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.vascular.arteriosclerosis",sWebLanguage,"ce3-c9")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_VASCULAR_DIAGNOSIS_DEEP_VENOUS_THROMBOSIS")%> type="checkbox" id="ce3-c10" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_DIAGNOSIS_DEEP_VENOUS_THROMBOSIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_DIAGNOSIS_DEEP_VENOUS_THROMBOSIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.vascular.deep-venous-thrombosis",sWebLanguage,"ce3-c10")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_VASCULAR_DIAGNOSIS_ANEURYSMA")%> type="checkbox" id="ce3-c11" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_DIAGNOSIS_ANEURYSMA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_DIAGNOSIS_ANEURYSMA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.vascular.aneurysma",sWebLanguage,"ce3-c11")%></td>
                </tr>
                <tr>
                    <td class="admin2" colspan="4"><input <%=setRightClick("ITEM_TYPE_VASCULAR_DIAGNOSIS_SUPERFICIAL_VENOUS_PHLEBITIS")%> type="checkbox" id="ce3-c12" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_DIAGNOSIS_SUPERFICIAL_VENOUS_PHLEBITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_DIAGNOSIS_SUPERFICIAL_VENOUS_PHLEBITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.vascular.superficial-phlebitis",sWebLanguage,"ce3-c12")%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.remark",sWebLanguage)%></td>
                    <td class="admin2" colspan="3">
                        <textarea onKeyup="resizeTextarea(this,10);limitChars(this,255);" <%=setRightClick("ITEM_TYPE_VASCULAR_DIAGNOSIS_OTHER")%> class="text" rows="2" cols="80" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_DIAGNOSIS_OTHER" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_VASCULAR_DIAGNOSIS_OTHER" property="value"/></textarea>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<%-- RESPIRATORY ---------------------------------------------------------------------------------%>
<br><br>
<table border='0' width='100%' height='100%' cellspacing="1" cellpadding="0" class="list">
    <tr class="admin">
        <td colspan="2"><%=getTran("Web.Occup","medwan.healthrecord.anamnese.respiratoire",sWebLanguage)%></td>
    </tr>
    <tr id="RESPIRATORY-details" width="100%">
        <td class="admin" width="25%">&nbsp;</td>
        <td class="admin2" width="*">
            <table width="100%">
                <tr>
                    <td width="33%"><input <%=setRightClick("ITEM_TYPE_RESPIRATORY_ANAMNESIS_COUGH")%> type="checkbox" id="ce3-c13" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_ANAMNESIS_COUGH" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_ANAMNESIS_COUGH;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.respiratory.cough",sWebLanguage,"ce3-c13")%></td>
                    <td width="33%"><input <%=setRightClick("ITEM_TYPE_RESPIRATORY_ANAMNESIS_EXPECTORATIONS")%> type="checkbox" id="ce3-c14" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_ANAMNESIS_EXPECTORATIONS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_ANAMNESIS_EXPECTORATIONS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.respiratory.expectorations",sWebLanguage,"ce3-c14")%></td>
                    <td width="33%"><input <%=setRightClick("ITEM_TYPE_RESPIRATORY_ANAMNESIS_HAEMOPTOE")%> type="checkbox" id="ce3-c15" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_ANAMNESIS_HAEMOPTOE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_ANAMNESIS_HAEMOPTOE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.respiratory.hemoptoe",sWebLanguage,"ce3-c15")%></td>
                </tr>
                <tr>
                    <td><input <%=setRightClick("ITEM_TYPE_RESPIRATORY_ANAMNESIS_THORACALGIA")%> type="checkbox" id="ce3-c16" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_ANAMNESIS_THORACALGIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_ANAMNESIS_THORACALGIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.respiratory.thoracalgia",sWebLanguage,"ce3-c16")%></td>
                    <td><input <%=setRightClick("ITEM_TYPE_RESPIRATORY_ANAMNESIS_DYSPNOE")%> type="checkbox" id="ce3-c17" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_ANAMNESIS_DYSPNOE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_ANAMNESIS_DYSPNOE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.respiratory.dyspnoe",sWebLanguage,"ce3-c17")%></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td class="title" colspan="2">
            <img src='<c:url value="/_img/themes/default/pijl.gif"/>'>
            <a href="#" onclick="toggle_id('medwan.healthrecord.respiratory-details');"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%> & <%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></a>
        </td>
    </tr>
    <tr id="medwan.healthrecord.respiratory-details" style="display:none">
        <td colspan="2">
            <table width="100%" class="list" cellspacing="1">
                <tr>
                    <td class="titleadmin" colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="titleadmin" colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.respiratory.auscultation",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_RESPIRATORY_CLINICAL_EXAMINATION_REUTELS")%> type="checkbox" id="ce3-c18" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_CLINICAL_EXAMINATION_REUTELS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_CLINICAL_EXAMINATION_REUTELS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.respiratory.reutels",sWebLanguage,"ce3-c18")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_RESPIRATORY_CLINICAL_EXAMINATION_WHEEZING")%> type="checkbox" id="ce3-c19" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_CLINICAL_EXAMINATION_WHEEZING" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_CLINICAL_EXAMINATION_WHEEZING;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.respiratory.wheezing",sWebLanguage,"ce3-c19")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_RESPIRATORY_CLINICAL_EXAMINATION_CREPITATIONS")%> type="checkbox" id="ce3-c20" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_CLINICAL_EXAMINATION_CREPITATIONS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_CLINICAL_EXAMINATION_CREPITATIONS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.respiratory.crepitations",sWebLanguage,"ce3-c20")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_RESPIRATORY_CLINICAL_EXAMINATION_SIBILANCES")%> type="checkbox" id="ce3-c21" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_CLINICAL_EXAMINATION_SIBILANCES" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_CLINICAL_EXAMINATION_SIBILANCES;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.respiratory.sibilances",sWebLanguage,"ce3-c21")%></td>
                </tr>
                <tr>
                    <td class="admin2" colspan="4"><input <%=setRightClick("ITEM_TYPE_RESPIRATORY_CLINICAL_EXAMINATION_VAG")%> type="checkbox" id="ce3-c22" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_CLINICAL_EXAMINATION_VAG" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_CLINICAL_EXAMINATION_VAG;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.respiratory.vag",sWebLanguage,"ce3-c22")%></td>
                </tr>
                <tr>
                    <td class="titleadmin" colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_RESPIRATORY_DIAGNOSIS_HAY_FEVER")%> type="checkbox" id="ce3-c23" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_DIAGNOSIS_HAY_FEVER" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_DIAGNOSIS_HAY_FEVER;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.respiratory.hay-fever",sWebLanguage,"ce3-c23")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_RESPIRATORY_DIAGNOSIS_DISTURBED_LUNG_FUNCTION")%> type="checkbox" id="ce3-c24" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_DIAGNOSIS_DISTURBED_LUNG_FUNCTION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_DIAGNOSIS_DISTURBED_LUNG_FUNCTION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.respiratory.disturbed-lung-function",sWebLanguage,"ce3-c24")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_RESPIRATORY_DIAGNOSIS_BPCO")%> type="checkbox" id="ce3-c25" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_DIAGNOSIS_BPCO" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_DIAGNOSIS_BPCO;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.respiratory.bpco",sWebLanguage,"ce3-c25")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_RESPIRATORY_DIAGNOSIS_TUBERCULOSIS")%> type="checkbox" id="ce3-c26" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_DIAGNOSIS_TUBERCULOSIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_DIAGNOSIS_TUBERCULOSIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.respiratory.tuberculosis",sWebLanguage,"ce3-c26")%></td>
                </tr>
                <tr>
                    <td class="admin2" colspan="4"><input <%=setRightClick("ITEM_TYPE_RESPIRATORY_DIAGNOSIS_ASTHMA")%> type="checkbox" id="ce3-c27" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_DIAGNOSIS_ASTHMA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_DIAGNOSIS_ASTHMA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.respiratory.asthma",sWebLanguage,"ce3-c27")%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.remark",sWebLanguage)%></td>
                    <td class="admin2" colspan="3">
                        <textarea onKeyup="resizeTextarea(this,10);limitChars(this,255);" <%=setRightClick("ITEM_TYPE_RESPIRATORY_DIAGNOSIS_OTHER")%> class="text" rows="2" cols="80" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_DIAGNOSIS_OTHER" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_RESPIRATORY_DIAGNOSIS_OTHER" property="value"/></textarea>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<%-- GASTRO --------------------------------------------------------------------------------------%>
<br><br>
<table border='0' width='100%' height='100%' cellspacing="1" cellpadding="0" class="list">
    <tr class="admin">
        <td colspan="2"><%=getTran("Web.Occup","medwan.healthrecord.anamnese.gastro-enterologique",sWebLanguage)%></td>
    </tr>
    <tr id="GASTRO-details">
        <td class="admin" width="25%">&nbsp;</td>
        <td class="admin2" width="*">
            <table width="100%">
                <tr>
                    <td width="33%"><input <%=setRightClick("ITEM_TYPE_GASTRO_ANAMNESIS_ANOREXIA")%> type="checkbox" id="ce3-c28" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_ANOREXIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_ANOREXIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.anorexia",sWebLanguage,"ce3-c28")%></td>
                    <td width="33%"><input <%=setRightClick("ITEM_TYPE_GASTRO_ANAMNESIS_PYROSIS")%> type="checkbox" id="ce3-c29" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_PYROSIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_PYROSIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.dysphagia",sWebLanguage,"ce3-c29")%></td>
                    <td width="33%"><input <%=setRightClick("ITEM_TYPE_GASTRO_ANAMNESIS_NAUSEA")%> type="checkbox" id="ce3-c30" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_NAUSEA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_NAUSEA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.nausea",sWebLanguage,"ce3-c30")%></td>
                </tr>
                <tr>
                    <td><input <%=setRightClick("ITEM_TYPE_GASTRO_ANAMNESIS_VOMITING")%> type="checkbox" id="ce3-c31" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_VOMITING" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_VOMITING;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.vomiting",sWebLanguage,"ce3-c31")%></td>
                    <td><input <%=setRightClick("ITEM_TYPE_GASTRO_ANAMNESIS_CONSTIPATION")%> type="checkbox" id="ce3-c32" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_CONSTIPATION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_CONSTIPATION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.constipation",sWebLanguage,"ce3-c32")%></td>
                    <td><input <%=setRightClick("ITEM_TYPE_GASTRO_ANAMNESIS_DIARRHEA")%> type="checkbox" id="ce3-c33" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_DIARRHEA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_DIARRHEA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.diarrhea",sWebLanguage,"ce3-c33")%></td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td class="title" colspan="2">
            <img src='<c:url value="/_img/themes/default/pijl.gif"/>'>
            <a href="#" onclick="toggle_id('medwan.healthrecord.gastro-details');"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%> & <%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></a>
        </td>
    </tr>
    <tr id="medwan.healthrecord.gastro-details" style="display:none">
        <td colspan="2">
            <table width="100%" class="admin" cellspacing="1">
                <tr>
                    <td class="titleadmin" colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="titleadmin" colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.gastro.inspection",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2" colspan="4"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_VERGETURES")%> type="checkbox" id="ce3-c34" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_VERGETURES" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_VERGETURES;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.vergetures",sWebLanguage,"ce3-c34")%></td>
                </tr>
                <tr>
                    <td class="titleadmin" colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.gastro.palpation",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PALPATION_PAIN")%> type="checkbox" id="ce3-c35" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PALPATION_PAIN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PALPATION_PAIN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.palpation-pain",sWebLanguage,"ce3-c35")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_RELEASE_PAIN")%> type="checkbox" id="ce3-c36" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_RELEASE_PAIN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_RELEASE_PAIN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.release-pain",sWebLanguage,"ce3-c36")%></td>
                    <td class="admin2" colspan="2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_HERNIA_PORTS")%> type="checkbox" id="ce3-c37" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_HERNIA_PORTS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_HERNIA_PORTS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.hernia-ports",sWebLanguage,"ce3-c37")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MAC_BURNEY")%> type="checkbox" id="ce3-c38" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MAC_BURNEY" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MAC_BURNEY;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.mac-burnney",sWebLanguage,"ce3-c38")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_LIVER_BORDER_FELT")%> type="checkbox" id="ce3-c39" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_LIVER_BORDER_FELT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_LIVER_BORDER_FELT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.liverborder-felt",sWebLanguage,"ce3-c39")%></td>
                    <td class="admin2" colspan="2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MURPHY")%> type="checkbox" id="ce3-c40" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MURPHY" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MURPHY;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.murphy",sWebLanguage,"ce3-c40")%></td>
                </tr>
                <tr>
                    <td class="titleadmin" colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.gastro.percussion",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2" colspan="4"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PERCUSSION")%> type="text" class="text" size="90" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PERCUSSION" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PERCUSSION" property="value"/>"></td>
                </tr>
                <tr>
                    <td class="titleadmin" colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="titleadmin" colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.common.tumors",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_OESOPHAGE_BENIGN")%> type="checkbox" id="ce3-c41" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_OESOPHAGE_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_OESOPHAGE_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors.oesophagus",sWebLanguage,"ce3-c41")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_STOMACH_BENIGN")%> type="checkbox" id="ce3-c42" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_STOMACH_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_STOMACH_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors.stomach",sWebLanguage,"ce3-c42")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BOWEL_BENIGN")%> type="checkbox" id="ce3-c43" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BOWEL_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BOWEL_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors.bowel",sWebLanguage,"ce3-c43")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_COLON_BENIGN")%> type="checkbox" id="ce3-c44" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_COLON_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_COLON_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors.colon",sWebLanguage,"ce3-c44")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_RECTUM_BENIGN")%> type="checkbox" id="ce3-c45" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_RECTUM_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_RECTUM_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors.rectum",sWebLanguage,"ce3-c45")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_ANAL_BENIGN")%> type="checkbox" id="ce3-c46" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_ANAL_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_ANAL_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors.anal",sWebLanguage,"ce3-c46")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_BLADDER_BENIGN")%> type="checkbox" id="ce3-c47" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_BLADDER_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_BLADDER_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors.billiary-bladder",sWebLanguage,"ce3-c47")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_LIVER_BENIGN")%> type="checkbox" id="ce3-c48" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_LIVER_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_LIVER_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors.liver",sWebLanguage,"ce3-c48")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_DUCT_BENIGN")%> type="checkbox" id="ce3-c49" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_DUCT_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_DUCT_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors.billiary-ducts",sWebLanguage,"ce3-c49")%></td>
                    <td class="admin2" colspan="3"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BENIGN")%> type="checkbox" id="ce3-c50" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors",sWebLanguage,"ce3-c50")%></td>
                </tr>
                <tr>
                    <td class="titleadmin" colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.common.other",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.gastro.other-oesophagel-disorders",sWebLanguage)%></td>
                    <td class="admin2" colspan="3"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_OESOPHAGAL_PROBLEMS")%> type="text" class="text" size="90" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_OESOPHAGAL_PROBLEMS" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_OESOPHAGAL_PROBLEMS" property="value"/>"></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_HERNIA_DIAPHRAGMATICA")%> type="checkbox" id="ce3-c51" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HERNIA_DIAPHRAGMATICA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HERNIA_DIAPHRAGMATICA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.hernia-diaphragmatica",sWebLanguage,"ce3-c51")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_HERNIA_DIAPHRAGMATICA")%> type="checkbox" id="ce3-c52" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HERNIA_DIAPHRAGMATICA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HERNIA_DIAPHRAGMATICA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.hernia-diaphragmatica",sWebLanguage,"ce3-c52")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_GASTRITIS")%> type="checkbox" id="ce3-c53" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_GASTRITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_GASTRITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.gastritis",sWebLanguage,"ce3-c53")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_GASTRIC_ULCER")%> type="checkbox" id="ce3-c54" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_GASTRIC_ULCER" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_GASTRIC_ULCER;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.stomach-ulcer",sWebLanguage,"ce3-c54")%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.gastro.other-stomach-disorders",sWebLanguage)%></td>
                    <td class="admin2" colspan="3"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_STOMACH_PROBLEM")%> type="text" class="text" size="90" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_STOMACH_PROBLEM" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_STOMACH_PROBLEM" property="value"/>"></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_DUODENUM_ULCER")%> type="checkbox" id="ce3-c55" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_DUODENUM_ULCER" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_DUODENUM_ULCER;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.duodenum-ulcer",sWebLanguage,"ce3-c55")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_CROHNS_DISEASE")%> type="checkbox" id="ce3-c56" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_CROHNS_DISEASE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_CROHNS_DISEASE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.crohns-disease",sWebLanguage,"ce3-c56")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_COLITIS_ULCEROSA")%> type="checkbox" id="ce3-c57" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_COLITIS_ULCEROSA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_COLITIS_ULCEROSA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.colitis-ulcerosa",sWebLanguage,"ce3-c57")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_CHRONIC_DIARRHEA")%> type="checkbox" id="ce3-c58" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_CHRONIC_DIARRHEA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_CHRONIC_DIARRHEA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.chronic-diarrhea",sWebLanguage,"ce3-c58")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_INGUINAL_HERNIA")%> type="checkbox" id="ce3-c59" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_INGUINAL_HERNIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_INGUINAL_HERNIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.inguinal-hernia",sWebLanguage,"ce3-c59")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_NAVEL_HERNIA")%> type="checkbox" id="ce3-c60" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_NAVEL_HERNIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_NAVEL_HERNIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.umbilical-hernia",sWebLanguage,"ce3-c60")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_BOWEL_POLYPS")%> type="checkbox" id="ce3-c61" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_BOWEL_POLYPS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_BOWEL_POLYPS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.bowel-polyps",sWebLanguage,"ce3-c61")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_IRRITABEL_BOWEL")%> type="checkbox" id="ce3-c62" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_IRRITABEL_BOWEL" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_IRRITABEL_BOWEL;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.irritable-bowel",sWebLanguage,"ce3-c62")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_HEMORRHOIDS")%> type="checkbox" id="ce3-c63" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HEMORRHOIDS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HEMORRHOIDS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.hemorrhoids",sWebLanguage,"ce3-c63")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_FISSURE")%> type="checkbox" id="ce3-c64" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_FISSURE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_FISSURE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.anal-fissura",sWebLanguage,"ce3-c64")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_ABCES")%> type="checkbox" id="ce3-c65" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_ABCES" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_ABCES;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.anal-abces",sWebLanguage,"ce3-c65")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_FISTULA")%> type="checkbox" id="ce3-c66" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_FISTULA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_FISTULA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.anal-fistula",sWebLanguage,"ce3-c66")%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.gastro.other-bowel-disorders",sWebLanguage)%></td>
                    <td class="admin2" colspan="3"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_BOWEL")%> type="text" class="text" size="90" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_BOWEL" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_BOWEL" property="value"/>"></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_LIVER_STEATOSIS")%> type="checkbox" id="ce3-c67" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_LIVER_STEATOSIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_LIVER_STEATOSIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.liver-steatosis",sWebLanguage,"ce3-c67")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_LIVER_CIRRHOSIS")%> type="checkbox" id="ce3-c68" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_LIVER_CIRRHOSIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_LIVER_CIRRHOSIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.liver-cirrhosis",sWebLanguage,"ce3-c68")%></td>
                    <td class="admin2" colspan="2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_CHOLECYSTITIS")%> type="checkbox" id="ce3-c69" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_CHOLECYSTITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_CHOLECYSTITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.cholecystitis",sWebLanguage,"ce3-c69")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_HEPATITIS_A")%> type="checkbox" id="ce3-c70" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HEPATITIS_A" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HEPATITIS_A;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.hepatitis-a",sWebLanguage,"ce3-c70")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_HEPATITIS_B")%> type="checkbox" id="ce3-c71" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HEPATITIS_B" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HEPATITIS_B;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.hepatitis-b",sWebLanguage,"ce3-c71")%></td>
                    <td class="admin2" colspan="2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_HEPATITIS_C")%> type="checkbox" id="ce3-c72" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HEPATITIS_C" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HEPATITIS_C;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.hepatitis-c",sWebLanguage,"ce3-c72")%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.remark",sWebLanguage)%></td>
                    <td class="admin2" colspan="3">
                        <textarea onKeyup="resizeTextarea(this,10);limitChars(this,255);" <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER")%> class="text" rows="2" cols="80" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER" property="value"/></textarea>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<%-- HEMATO --------------------------------------------------------------------------------------%>
<br><br>
<table border='0' width='100%' height='100%' cellspacing="1" cellpadding="0" class="list">
    <tr class="admin">
        <td><%=getTran("Web.Occup","medwan.healthrecord.anamnese.hematologique",sWebLanguage)%></td>
    </tr>
    <tr id="HEMATO-details" width="100%">
        <td class="title">
            <img src='<c:url value="/_img/themes/default/pijl.gif"/>'>
            <a href="#" onclick="toggle_id('medwan.healthrecord.hemato-details');"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%> & <%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></a>
        </td>
    </tr>
    <tr id="medwan.healthrecord.hemato-details" style="display:none">
        <td>
            <table width="100%" cellspacing="1" class="list">
                <tr>
                    <td class="titleadmin" colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="titleadmin" colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.hemato.palpation",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2" colspan="4"><input <%=setRightClick("ITEM_TYPE_HEMATO_CLINICAL_EXAMINATION_SPLEEN_ENLARGED")%> type="checkbox" id="ce3-c73" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_CLINICAL_EXAMINATION_SPLEEN_ENLARGED" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_CLINICAL_EXAMINATION_SPLEEN_ENLARGED;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.hemato.spleen-enlargement",sWebLanguage,"ce3-c73")%></td>
                </tr>
                <tr>
                    <td class="titleadmin" colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="titleadmin" colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.common.tumors",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_HEMATO_DIAGNOSIS_TUMOR_LEUKEMIA")%> type="checkbox" id="ce3-c74" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_TUMOR_LEUKEMIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_TUMOR_LEUKEMIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors.leukemia",sWebLanguage,"ce3-c74")%></td>
                    <td class="admin2" colspan="3"><input <%=setRightClick("ITEM_TYPE_HEMATO_DIAGNOSIS_TUMOR_LYMPHOMA")%> type="checkbox" id="ce3-c75" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_TUMOR_LYMPHOMA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_TUMOR_LYMPHOMA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.tumors.hodgkin",sWebLanguage,"ce3-c75")%></td>
                </tr>
                <tr>
                    <td class="titleadmin" colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.common.other",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_HEMATO_DIAGNOSIS_COAGULATION_DISORDERS")%> type="checkbox" id="ce3-c76" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_COAGULATION_DISORDERS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_COAGULATION_DISORDERS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.hemato.coagulation-disorders",sWebLanguage,"ce3-c76")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_HEMATO_DIAGNOSIS_THROMBOCYTOPENIA")%> type="checkbox" id="ce3-c77" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_THROMBOCYTOPENIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_THROMBOCYTOPENIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.hemato.thrombocytopenia",sWebLanguage,"ce3-c77")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_HEMATO_DIAGNOSIS_LEUCOPENIA")%> type="checkbox" id="ce3-c78" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_LEUCOPENIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_LEUCOPENIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.hemato.leukopenia",sWebLanguage,"ce3-c78")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_HEMATO_DIAGNOSIS_FERRIPRIVE_ANEMIA")%> type="checkbox" id="ce3-c79" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_FERRIPRIVE_ANEMIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_FERRIPRIVE_ANEMIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.hemato.ferriprive-anemia",sWebLanguage,"ce3-c79")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_HEMATO_DIAGNOSIS_OTHER_ANEMIA")%> type="checkbox" id="ce3-c80" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_OTHER_ANEMIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_OTHER_ANEMIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.hemato.other-anemia",sWebLanguage,"ce3-c80")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_HEMATO_DIAGNOSIS_HEMOCHROMATOSIS")%> type="checkbox" id="ce3-c81" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_HEMOCHROMATOSIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_HEMOCHROMATOSIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.hemato.hemochromatosis",sWebLanguage,"ce3-c81")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_HEMATO_DIAGNOSIS_SPLEEN_AFFECTION")%> type="checkbox" id="ce3-c82" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_SPLEEN_AFFECTION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_SPLEEN_AFFECTION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.hemato.spleen-affection",sWebLanguage,"ce3-c82")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_HEMATO_DIAGNOSIS_MALARIA")%> type="checkbox" id="ce3-c83" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_MALARIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_MALARIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.hemato.malaria",sWebLanguage,"ce3-c83")%></td>
                </tr>
                <tr>
                    <td class="admin2" colspan="4"><input <%=setRightClick("ITEM_TYPE_HEMATO_DIAGNOSIS_AIDS")%> type="checkbox" id="ce3-c84" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_AIDS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_AIDS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.hemato.aids",sWebLanguage,"ce3-c84")%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.remark",sWebLanguage)%></td>
                    <td class="admin2" colspan="3">
                        <textarea onKeyup="resizeTextarea(this,10);limitChars(this,255);" <%=setRightClick("ITEM_TYPE_HEMATO_DIAGNOSIS_OTHER")%> class="text" rows="2" cols="80" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_OTHER" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_HEMATO_DIAGNOSIS_OTHER" property="value"/></textarea>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>