<%@include file="/includes/validateUser.jsp"%>
<%@page errorPage="/includes/error.jsp"%>
<%
    
%>
<form name="transactionForm" method="POST" action='<c:url value="/healthrecord/updateTransaction.do"/>?ts=<%=getTs()%>' onclick="setSaveButton();" onkeyup="setSaveButton();">
    <bean:define id="transaction" name="be.mxs.webapp.wl.session.SessionContainerFactory.WO_SESSION_CONTAINER" property="currentTransactionVO"/>

    <input id="serverId" type="hidden" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.serverId" value="<bean:write name="transaction" scope="page" property="serverId"/>"/>
    <input id="transactionId" type="hidden" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.transactionId" value="<bean:write name="transaction" scope="page" property="transactionId"/>"/>
    <input type="hidden" name="subClass" value="URO"/>
    <input id="transactionType" type="hidden" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.transactionType" value="<bean:write name="transaction" scope="page" property="transactionType"/>"/>
    <input type="hidden" readonly name="be.mxs.healthrecord.updateTransaction.actionForwardKey" value="/healthrecord/editTransaction.do?be.mxs.healthrecord.createTransaction.transactionType=<bean:write name="transaction" scope="page" property="transactionType"/>&be.mxs.healthrecord.transaction_id=currentTransaction&ts=<%=getTs()%>"/>
    <input type="hidden" readonly name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_RAS" property="itemId"/>]>.value" value="medwan.common.false"/>

<script>
  function setTrue(itemType){
    var fieldName;
    fieldName = "currentTransactionVO.items.<ItemVO[hashCode="+itemType+"]>.value";
    document.getElementsByName(fieldName)[0].value = "medwan.common.true";
  }

  function setFalse(itemType){
    var fieldName;
    fieldName = "currentTransactionVO.items.<ItemVO[hashCode="+itemType+"]>.value";
    document.getElementsByName(fieldName)[0].value = "medwan.common.false";
  }
</script>

<table width="100%" class="list" cellspacing="0">
    <tr class="admin">
        <td><%=getTran("Web.Occup","medwan.healthrecord.anamnese.uro-renal",sWebLanguage)%></td>
        <td align="right" width="20%">
            <%=getLabel("Web.Occup","medwan.common.nothing-to-mention",sWebLanguage,"uro-c1")%>&nbsp;<input name="uro-ras" type="checkbox" id="uro-c1" value="medwan.common.true" onclick="if (this.checked == true) {hide('URO-details');setTrue('<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_RAS" property="itemId"/>'); } else {show('URO-details');setFalse('<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_RAS" property="itemId"/>'); }">
        </td>
        <td align="right" width ="1%"><a href="#top" class="topbutton">&nbsp;</a></td>
    </tr>
    <tr id="URO-details" style="display:none" width="100%">
        <td colspan="4" width="100%">
            <table width="100%" cellspacing="1">
                <tr class="admin">
                    <td colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.anamnese",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_ANAMNESIS_MICTALGIA")%> type="checkbox" id="uro-c2" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_ANAMNESIS_MICTALGIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_ANAMNESIS_MICTALGIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.mictalgia",sWebLanguage,"uro-c2")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_ANAMNESIS_OLIGURIA")%> type="checkbox" id="uro-c3" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_ANAMNESIS_OLIGURIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_ANAMNESIS_OLIGURIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.oliguria",sWebLanguage,"uro-c3")%></td>
                    <td class="admin2" colspan="2"><input <%=setRightClick("ITEM_TYPE_URO_ANAMNESIS_MACROSCOPIC_HEMATURIA")%> type="checkbox" id="uro-c4" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_ANAMNESIS_MACROSCOPIC_HEMATURIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_ANAMNESIS_MACROSCOPIC_HEMATURIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.macroscopic-haematuria",sWebLanguage,"uro-c4")%></td>
                </tr>
                <tr class="admin">
                    <td colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%></td>
                </tr>
                <tr class="admin">
                    <td colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.uro.palpation",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_CLINICAL_EXAMINATION_LUMBAL_STROKE_PAIN")%> type="checkbox" id="uro-c5" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_CLINICAL_EXAMINATION_LUMBAL_STROKE_PAIN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_CLINICAL_EXAMINATION_LUMBAL_STROKE_PAIN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.lumbal-stroke-pain",sWebLanguage,"uro-c5")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_CLINICAL_EXAMINATION_RENAL_BALLOTTAGE")%> type="checkbox" id="uro-c6" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_CLINICAL_EXAMINATION_RENAL_BALLOTTAGE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_CLINICAL_EXAMINATION_RENAL_BALLOTTAGE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.renal-ballotage",sWebLanguage,"uro-c6")%></td>
                    <td class="admin2" colspan="2"><input <%=setRightClick("ITEM_TYPE_URO_CLINICAL_EXAMINATION_RENAL_ENLARGEMENT")%> type="checkbox" id="uro-c7" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_CLINICAL_EXAMINATION_RENAL_ENLARGEMENT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_CLINICAL_EXAMINATION_RENAL_ENLARGEMENT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.renal-enlargement",sWebLanguage,"uro-c7")%></td>
                </tr>
                <tr class="admin">
                    <td colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></td>
                </tr>
                <tr class="admin">
                    <td colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.common.tumors",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin" width="25%"><%=getTran("Web.Occup","medwan.common.tumors.kidney",sWebLanguage)%></td>
                    <td class="admin2" width="25%">
                        <input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_TUMOR_KIDNEY_BENIGN")%> type="checkbox" id="uro-c8" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_TUMOR_KIDNEY_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_TUMOR_KIDNEY_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.benign",sWebLanguage,"uro-c8")%>
                        <input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_TUMOR_KIDNEY_MALIGNANT")%> type="checkbox" id="uro-c9" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_TUMOR_KIDNEY_MALIGNANT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_TUMOR_KIDNEY_MALIGNANT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.malignant",sWebLanguage,"uro-c9")%>
                    </td>
                    <td class="admin" width="25%"><%=getTran("Web.Occup","medwan.common.tumors.bladder",sWebLanguage)%></td>
                    <td class="admin2" width="25%">
                        <input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_TUMOR_BLADDER_BENIGN")%> type="checkbox" id="uro-c10" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_TUMOR_BLADDER_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_TUMOR_BLADDER_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.benign",sWebLanguage,"uro-c10")%>
                        <input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_TUMOR_BLADDER_MALIGNANT")%> type="checkbox" id="uro-c11" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_TUMOR_BLADDER_MALIGNANT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_TUMOR_BLADDER_MALIGNANT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.malignant",sWebLanguage,"uro-c11")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.tumors.prostate",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_TUMOR_TESTIS_BENIGN")%> type="checkbox" id="uro-c12" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_TUMOR_TESTIS_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_TUMOR_TESTIS_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.benign",sWebLanguage,"uro-c12")%>
                        <input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_TUMOR_TESTIS_MALIGNANT")%> type="checkbox" id="uro-c13" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_TUMOR_TESTIS_MALIGNANT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_TUMOR_TESTIS_MALIGNANT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.malignant",sWebLanguage,"uro-c13")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.tumors.testis",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_TUMOR_PROSTATE_BENIGN")%> type="checkbox" id="uro-c14" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_TUMOR_PROSTATE_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_TUMOR_PROSTATE_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.benign",sWebLanguage,"uro-c14")%>
                        <input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_TUMOR_PROSTATE_MALIGNANT")%> type="checkbox" id="uro-c15" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_TUMOR_PROSTATE_MALIGNANT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_TUMOR_PROSTATE_MALIGNANT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.malignant",sWebLanguage,"uro-c15")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.tumors",sWebLanguage)%></td>
                    <td class="admin2" colspan="3">
                        <input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_TUMOR_BENIGN")%> type="checkbox" id="uro-c16" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_TUMOR_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_TUMOR_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.benign",sWebLanguage,"uro-c16")%>
                        <input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_TUMOR_MALIGNANT")%> type="checkbox" id="uro-c17" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_TUMOR_MALIGNANT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_TUMOR_MALIGNANT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.malignant",sWebLanguage,"uro-c17")%>
                    </td>
                </tr>
                <tr class="admin">
                    <td colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.common.other",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_ACUTE_RENAL_INSUFFICIENCY")%> type="checkbox" id="uro-c18" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_ACUTE_RENAL_INSUFFICIENCY" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_ACUTE_RENAL_INSUFFICIENCY;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.acute-renal-insufficiency",sWebLanguage,"uro-c18")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_CHRONIC_RENAL_INSUFFICIENCY")%> type="checkbox" id="uro-c19" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_CHRONIC_RENAL_INSUFFICIENCY" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_CHRONIC_RENAL_INSUFFICIENCY;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.chronic-renal-insufficiency",sWebLanguage,"uro-c19")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_ACUTE_GLOMERULONEPHRITIS")%> type="checkbox" id="uro-c20" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_ACUTE_GLOMERULONEPHRITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_ACUTE_GLOMERULONEPHRITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.acute-glomerulonephritis",sWebLanguage,"uro-c20")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_CHRONIC_GLOMERULONEPHRITIS")%> type="checkbox" id="uro-c21" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_CHRONIC_GLOMERULONEPHRITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_CHRONIC_GLOMERULONEPHRITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.chronic-glomerulonephritis",sWebLanguage,"uro-c21")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_POLYCYSTIC_KIDNEYS")%> type="checkbox" id="uro-c22" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_POLYCYSTIC_KIDNEYS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_POLYCYSTIC_KIDNEYS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.polycystic-kidneys",sWebLanguage,"uro-c22")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_HYDRONEPHROSIS")%> type="checkbox" id="uro-c23" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_HYDRONEPHROSIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_HYDRONEPHROSIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.hydronephrosis",sWebLanguage,"uro-c23")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_RENAL_DIALYSIS")%> type="checkbox" id="uro-c24" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_RENAL_DIALYSIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_RENAL_DIALYSIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.renal-dialysis",sWebLanguage,"uro-c24")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_NEPHROTIC_SYNDROME")%> type="checkbox" id="uro-c25" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_NEPHROTIC_SYNDROME" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_NEPHROTIC_SYNDROME;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.nephrotic-syndrome",sWebLanguage,"uro-c25")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_RENAL_HYPERTENSION")%> type="checkbox" id="uro-c26" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_RENAL_HYPERTENSION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_RENAL_HYPERTENSION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.renal-hypertension",sWebLanguage,"uro-c26")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_RENAL_GLUCOSURIA")%> type="checkbox" id="uro-c27" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_RENAL_GLUCOSURIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_RENAL_GLUCOSURIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.renal-glycosuria",sWebLanguage,"uro-c27")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_ALBUMINURIA")%> type="checkbox" id="uro-c28" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_ALBUMINURIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_ALBUMINURIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.albuminuria",sWebLanguage,"uro-c28")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_HEMATURIA")%> type="checkbox" id="uro-c29" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_HEMATURIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_HEMATURIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.haematuria",sWebLanguage,"uro-c29")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_IDIOPATHIC_HEMATURIA")%> type="checkbox" id="uro-c30" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_IDIOPATHIC_HEMATURIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_IDIOPATHIC_HEMATURIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.idiopathic-haematuria",sWebLanguage,"uro-c30")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_KIDNEY_STONE")%> type="checkbox" id="uro-c31" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_KIDNEY_STONE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_KIDNEY_STONE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.kidney-stone",sWebLanguage,"uro-c31")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_URETER_STONE")%> type="checkbox" id="uro-c32" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_URETER_STONE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_URETER_STONE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.ureter-stone",sWebLanguage,"uro-c32")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_BLADDER_STONE")%> type="checkbox" id="uro-c33" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_BLADDER_STONE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_BLADDER_STONE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.bladder-stone",sWebLanguage,"uro-c33")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_PYELONEPHRITIS")%> type="checkbox" id="uro-c34" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_PYELONEPHRITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_PYELONEPHRITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.pyelonephritis",sWebLanguage,"uro-c34")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_CYSTITIS")%> type="checkbox" id="uro-c35" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_CYSTITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_CYSTITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.cystitis",sWebLanguage,"uro-c35")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_URETRITIS")%> type="checkbox" id="uro-c36" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_URETRITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_URETRITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.uretritis",sWebLanguage,"uro-c36")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_BLADDER_POLYP")%> type="checkbox" id="uro-c37" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_BLADDER_POLYP" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_BLADDER_POLYP;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.bladder-polyp",sWebLanguage,"uro-c37")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_URINARY_INCONTINENCY")%> type="checkbox" id="uro-c38" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_URINARY_INCONTINENCY" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_URINARY_INCONTINENCY;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.urinary-incontinency",sWebLanguage,"uro-c38")%></td>
                    <td class="admin2" colspan="3"><input <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_CONGENITAL_DISORDER")%> type="checkbox" id="uro-c39" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_CONGENITAL_DISORDER" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_CONGENITAL_DISORDER;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.uro.congenital-disorders",sWebLanguage,"uro-c39")%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.remark",sWebLanguage)%></td>
                    <td class="admin2" colspan="3">
                        <textarea onKeyup="resizeTextarea(this,10);limitChars(this,255);" <%=setRightClick("ITEM_TYPE_URO_DIAGNOSIS_OTHER")%> class="text" rows="2" cols="80" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_OTHER" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_URO_DIAGNOSIS_OTHER" property="value"/></textarea>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<%-- BUTTONS --%>
<%=ScreenHelper.alignButtonsStart()%>
    <INPUT class="button" type="button" name="saveButton" onClick="doSubmit();" value="<%=getTran("Web.Occup","medwan.common.record",sWebLanguage)%>">
    <INPUT class="button" type="button" value="<%=getTran("Web","Back",sWebLanguage)%>" onclick="if(checkSaveButton())){window.location.href='<c:url value='/healthrecord/editTransaction.do'/>?be.mxs.healthrecord.createTransaction.transactionType=<bean:write name="transaction" scope="page" property="transactionType"/>&be.mxs.healthrecord.transaction_id=currentTransaction&ts=<%=getTs()%>'}">
    <%=writeResetButton("transactionForm",sWebLanguage)%>
<%=ScreenHelper.alignButtonsStop()%>

<script>
  function doSubmit(){
    transactionForm.saveButton.disabled = true;
    <%
        SessionContainerWO sessionContainerWO = (SessionContainerWO)SessionContainerFactory.getInstance().getSessionContainerWO(request,SessionContainerWO.class.getName());
        out.print(takeOverTransaction(sessionContainerWO, activeUser,"document.transactionForm.submit();"));
    %>
  }

  document.getElementsByName('uro-ras')[0].onclick();
</script>

</form>
<%=writeJSButtons("transactionForm", "document.getElementsByName('save')[0]")%>