<%@ page import="java.util.GregorianCalendar"%>
<%@ include file="/includes/validateUser.jsp"%>
<%@page errorPage="/includes/error.jsp"%>

<form name="transactionForm" method="POST" action='<c:url value="/healthrecord/updateTransaction.do"/>?ts=<%=getTs()%>' onclick="setSaveButton();" onkeyup="setSaveButton();">

    <bean:define id="transaction" name="be.mxs.webapp.wl.session.SessionContainerFactory.WO_SESSION_CONTAINER" property="currentTransactionVO"/>

    <input type="hidden" name="subClass" value="GASTRO"/>
    <input id="transactionId" type="hidden" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.transactionId" value="<bean:write name="transaction" scope="page" property="transactionId"/>"/>
    <input type="hidden" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.transactionType" value="<bean:write name="transaction" scope="page" property="transactionType"/>"/>
    <input id="serverId" type="hidden" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.serverId" value="<bean:write name="transaction" scope="page" property="serverId"/>"/>
    <input type="hidden" readonly name="be.mxs.healthrecord.updateTransaction.actionForwardKey" value="/healthrecord/editTransaction.do?be.mxs.healthrecord.createTransaction.transactionType=<bean:write name="transaction" scope="page" property="transactionType"/>&be.mxs.healthrecord.transaction_id=currentTransaction&ts=<%=getTs()%>"/>
    <input type="hidden" readonly name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_RAS" property="itemId"/>]>.value" value="medwan.common.false"/>

<script>
  function setTrue(itemType){
    var fieldName;
    fieldName = "currentTransactionVO.items.<ItemVO[hashCode="+itemType+"]>.value";
    document.getElementsByName(fieldName)[0].value = "medwan.common.true";
  }

  function setFalse(itemType){
    var fieldName;
    fieldName = "currentTransactionVO.items.<ItemVO[hashCode="+itemType+"]>.value";
    document.getElementsByName(fieldName)[0].value = "medwan.common.false";
  }
</script>

<table width="100%" class="list" cellspacing="0">
    <tr class="admin">
        <td><%=getTran("Web.Occup","medwan.healthrecord.anamnese.gastro-enterologique",sWebLanguage)%></td>
        <td align="right" width="20%">
            <%=getLabel("Web.Occup","medwan.common.nothing-to-mention",sWebLanguage,"mceg-c1")%>&nbsp;<input name="gastro-ras" type="checkbox" id="mceg-c1" value="medwan.common.true" onclick="if (this.checked == true) {hide('GASTRO-details');setTrue('<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_RAS" property="itemId"/>'); } else {show('GASTRO-details');setFalse('<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_RAS" property="itemId"/>'); }">
        </td>
        <td align="right" width ="1%"><a class="topbutton" href="#top">&nbsp;</a></td>
    </tr>
    <tr id="GASTRO-details" style="display:none" width="100%">
        <td colspan="4" width="100%">
            <table width="100%" cellspacing="1">
                <tr class="admin">
                    <td colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.anamnese",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_GASTRO_ANAMNESIS_ANOREXIA")%> type="checkbox" id="mceg-c2" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_ANOREXIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_ANOREXIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.anorexia",sWebLanguage,"mceg-c2")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_GASTRO_ANAMNESIS_DYSPHAGIA")%> type="checkbox" id="mceg-c3" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_DYSPHAGIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_DYSPHAGIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.dysphagia",sWebLanguage,"mceg-c3")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_GASTRO_ANAMNESIS_NAUSEA")%> type="checkbox" id="mceg-c4" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_NAUSEA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_NAUSEA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.nausea",sWebLanguage,"mceg-c4")%></td>
                    <td class="admin2" width="25%"><input <%=setRightClick("ITEM_TYPE_GASTRO_ANAMNESIS_VOMITING")%> type="checkbox" id="mceg-c5" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_VOMITING" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_VOMITING;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.vomiting",sWebLanguage,"mceg-c5")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_ANAMNESIS_CONSTIPATION")%> type="checkbox" id="mceg-c6" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_CONSTIPATION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_CONSTIPATION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.constipation",sWebLanguage,"mceg-c6")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_ANAMNESIS_DIARRHEA")%> type="checkbox" id="mceg-c7" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_DIARRHEA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_DIARRHEA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.diarrhea",sWebLanguage,"mceg-c7")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_ANAMNESIS_PALE_STOOL")%> type="checkbox" id="mceg-c8" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_PALE_STOOL" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_PALE_STOOL;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.pale-stool",sWebLanguage,"mceg-c8")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_ANAMNESIS_DARK_URINE")%> type="checkbox" id="mceg-c9" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_DARK_URINE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_ANAMNESIS_DARK_URINE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.dark-urine",sWebLanguage,"mceg-c9")%></td>
                </tr>
                <tr class="admin">
                    <td colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%></td>
                </tr>
                <tr class="admin">
                    <td colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.gastro.inspection",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_BLOATED_ABDOMEN")%> type="checkbox" id="mceg-c10" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_BLOATED_ABDOMEN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_BLOATED_ABDOMEN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.bloated-abdomen",sWebLanguage,"mceg-c10")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_ASCITES")%> type="checkbox" id="mceg-c11" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_ASCITES" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_ASCITES;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.ascites",sWebLanguage,"mceg-c11")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_STRIAE")%> type="checkbox" id="mceg-c12" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_STRIAE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_STRIAE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.striae",sWebLanguage,"mceg-c12")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_ICTERUS")%> type="checkbox" id="mceg-c13" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_ICTERUS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_ICTERUS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.icterus",sWebLanguage,"mceg-c13")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_COLLATERAL_VENOUS_CIRCULATION")%> type="checkbox" id="mceg-c14" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_COLLATERAL_VENOUS_CIRCULATION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_COLLATERAL_VENOUS_CIRCULATION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.collateral-venous-circulation",sWebLanguage,"mceg-c14")%></td>
                    <td class="admin2" colspan="3"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_ARTERIAL_SPIDERS")%> type="checkbox" id="mceg-c15" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_ARTERIAL_SPIDERS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_ARTERIAL_SPIDERS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.arterial-spiders",sWebLanguage,"mceg-c15")%></td>
                </tr>
                <tr class="admin">
                    <td colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.gastro.palpation",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PALPATION_PAIN")%> type="checkbox" id="mceg-c16" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PALPATION_PAIN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PALPATION_PAIN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.palpation-pain",sWebLanguage,"mceg-c16")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_RELEASE_PAIN")%> type="checkbox" id="mceg-c17" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_RELEASE_PAIN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_RELEASE_PAIN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.release-pain",sWebLanguage,"mceg-c17")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_RESISTANCE")%> type="checkbox" id="mceg-c18" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_RESISTANCE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_RESISTANCE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.resistance",sWebLanguage,"mceg-c18")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_HERNIA_PORTS")%> type="checkbox" id="mceg-c19" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_HERNIA_PORTS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_HERNIA_PORTS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.hernia-ports",sWebLanguage,"mceg-c19")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PULSATING_TUMOR")%> type="checkbox" id="mceg-c20" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PULSATING_TUMOR" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PULSATING_TUMOR;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.pulsating-tumor",sWebLanguage,"mceg-c20")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MAC_BURNEY")%> type="checkbox" id="mceg-c21" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MAC_BURNEY" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MAC_BURNEY;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.mac-burnney",sWebLanguage,"mceg-c21")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_LIVER_BORDER_FELT")%> type="checkbox" id="mceg-c22" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_LIVER_BORDER_FELT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_LIVER_BORDER_FELT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.murphy",sWebLanguage,"mceg-c22")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MURPHY")%> type="checkbox" id="mceg-c23" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MURPHY" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MURPHY;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.liverborder-felt",sWebLanguage,"mceg-c23")%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.gastro.morphology-liverborder",sWebLanguage)%></td>
                    <td class="admin2" colspan="3"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MORPHOLOGY_LIVER_BORDER")%> type="text" class="text" size="90" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MORPHOLOGY_LIVER_BORDER" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_MORPHOLOGY_LIVER_BORDER" property="value"/>" onblur="limitLength(this);"></td>
                </tr>
                <tr class="admin">
                    <td colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.gastro.percussion",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2" colspan="4"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PERCUSSION")%> type="text" class="text" size="90" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PERCUSSION" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PERCUSSION" property="value"/>" onblur="limitLength(this);"></td>
                </tr>
                <tr class="admin">
                    <td colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.healthrecord.gastro.auscultation",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PERISTALSIS")%> type="checkbox" id="mceg-c24" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PERISTALSIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_PERISTALSIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.bowel-peristalsis",sWebLanguage,"mceg-c24")%></td>
                    <td class="admin2" colspan="3"><input <%=setRightClick("ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_VESSEL_NOISES")%> type="checkbox" id="mceg-c25" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_VESSEL_NOISES" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_CLINICAL_EXAMINATION_VESSEL_NOISES;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.vessel-noises",sWebLanguage,"mceg-c25")%></td>
                </tr>
                <tr class="admin">
                    <td colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></td>
                </tr>
                <tr class="admin">
                    <td colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.common.tumors",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.tumors.oesophagus",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_OESOPHAGE_BENIGN")%> type="checkbox" id="mceg-c26" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_OESOPHAGE_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_OESOPHAGE_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.benign",sWebLanguage,"mceg-c26")%>
                        <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_OESOPHAGE_MALIGNANT")%> type="checkbox" id="mceg-c27" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_OESOPHAGE_MALIGNANT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_OESOPHAGE_MALIGNANT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.malignant",sWebLanguage,"mceg-c27")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.tumors.stomach",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_STOMACH_BENIGN")%> type="checkbox" id="mceg-c28" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_STOMACH_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_STOMACH_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.benign",sWebLanguage,"mceg-c28")%>
                        <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_STOMACH_MALIGNANT")%> type="checkbox" id="mceg-c29" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_STOMACH_MALIGNANT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_STOMACH_MALIGNANT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.malignant",sWebLanguage,"mceg-c29")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.tumors.bowel",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BOWEL_BENIGN")%> type="checkbox" id="mceg-c30" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BOWEL_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BOWEL_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.benign",sWebLanguage,"mceg-c30")%>
                        <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BOWEL_MALIGNANT")%> type="checkbox" id="mceg-c31" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BOWEL_MALIGNANT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BOWEL_MALIGNANT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.malignant",sWebLanguage,"mceg-c31")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.tumors.colon",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_COLON_BENIGN")%> type="checkbox" id="mceg-c32" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_COLON_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_COLON_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.benign",sWebLanguage,"mceg-c32")%>
                        <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_COLON_MALIGNANT")%> type="checkbox" id="mceg-c33" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_COLON_MALIGNANT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_COLON_MALIGNANT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.malignant",sWebLanguage,"mceg-c33")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.tumors.rectum",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_RECTUM_BENIGN")%> type="checkbox" id="mceg-c34" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_RECTUM_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_RECTUM_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.benign",sWebLanguage,"mceg-c34")%>
                        <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_RECTUM_MALIGNANT")%> type="checkbox" id="mceg-c35" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_RECTUM_MALIGNANT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_RECTUM_MALIGNANT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.malignant",sWebLanguage,"mceg-c35")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.tumors.anal",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_ANAL_BENIGN")%> type="checkbox" id="mceg-c36" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_ANAL_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_ANAL_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.benign",sWebLanguage,"mceg-c36")%>
                        <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_ANAL_MALIGNANT")%> type="checkbox" id="mceg-c37" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_ANAL_MALIGNANT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_ANAL_MALIGNANT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.malignant",sWebLanguage,"mceg-c37")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.tumors.billiary-bladder",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_BLADDER_BENIGN")%> type="checkbox" id="mceg-c38" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_BLADDER_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_BLADDER_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.benign",sWebLanguage,"mceg-c38")%>
                        <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_BLADDER_MALIGNANT")%> type="checkbox" id="mceg-c39" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_BLADDER_MALIGNANT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_BLADDER_MALIGNANT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.malignant",sWebLanguage,"mceg-c39")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.tumors.liver",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_LIVER_BENIGN")%> type="checkbox" id="mceg-c40" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_LIVER_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_LIVER_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.benign",sWebLanguage,"mceg-c40")%>
                        <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_LIVER_MALIGNANT")%> type="checkbox" id="mceg-c41" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_LIVER_MALIGNANT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_LIVER_MALIGNANT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.malignant",sWebLanguage,"mceg-c41")%>
                    </td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.tumors.billiary-ducts",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_DUCT_BENIGN")%> type="checkbox" id="mceg-c42" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_DUCT_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_DUCT_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.benign",sWebLanguage,"mceg-c42")%>
                        <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_DUCT_MALIGNANT")%> type="checkbox" id="mceg-c43" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_DUCT_MALIGNANT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BILIARY_DUCT_MALIGNANT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.malignant",sWebLanguage,"mceg-c43")%>
                    </td>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.tumors",sWebLanguage)%></td>
                    <td class="admin2">
                        <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BENIGN")%> type="checkbox" id="mceg-c44" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BENIGN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_BENIGN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.benign",sWebLanguage,"mceg-c44")%>
                        <input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_MALIGNANT")%> type="checkbox" id="mceg-c45" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_MALIGNANT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_TUMOR_MALIGNANT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.malignant",sWebLanguage,"mceg-c45")%>
                    </td>
                </tr>
                <tr class="admin">
                    <td colspan="4">&nbsp; - <%=getTran("Web.Occup","medwan.common.other",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_OESOPHAGAL_SPASM")%> type="checkbox" id="mceg-c46" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OESOPHAGAL_SPASM" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OESOPHAGAL_SPASM;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.oesophagal-spasm",sWebLanguage,"mceg-c46")%></td>
                    <td class="admin2" colspan="3"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_OESOPHAGITIS")%> type="checkbox" id="mceg-c47" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OESOPHAGITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OESOPHAGITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.oesophagites",sWebLanguage,"mceg-c47")%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.gastro.other-oesophagel-disorders",sWebLanguage)%></td>
                    <td class="admin2" colspan="3"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_OESOPHAGAL_PROBLEMS")%> type="text" class="text" size="90" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_OESOPHAGAL_PROBLEMS" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_OESOPHAGAL_PROBLEMS" property="value"/>" onblur="limitLength(this);"></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_HERNIA_DIAPHRAGMATICA")%> type="checkbox" id="mceg-c48" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HERNIA_DIAPHRAGMATICA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HERNIA_DIAPHRAGMATICA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.hernia-diaphragmatica",sWebLanguage,"mceg-c48")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_GASTRITIS")%> type="checkbox" id="mceg-c49" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_GASTRITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_GASTRITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.gastritis",sWebLanguage,"mceg-c49")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_GASTRIC_ULCER")%> type="checkbox" id="mceg-c50" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_GASTRIC_ULCER" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_GASTRIC_ULCER;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.stomach-ulcer",sWebLanguage,"mceg-c50")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_PYLORIC_STENOSIS")%> type="checkbox" id="mceg-c51" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_PYLORIC_STENOSIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_PYLORIC_STENOSIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.pylorus-stenosis",sWebLanguage,"mceg-c51")%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.gastro.other-stomach-disorders",sWebLanguage)%></td>
                    <td class="admin2" colspan="3"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_STOMACH_PROBLEM")%> type="text" class="text" size="90" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_STOMACH_PROBLEM" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_STOMACH_PROBLEM" property="value"/>" onblur="limitLength(this);"></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_DUODENUM_ULCER")%> type="checkbox" id="mceg-c52" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_DUODENUM_ULCER" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_DUODENUM_ULCER;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.duodenum-ulcer",sWebLanguage,"mceg-c52")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_CROHNS_DISEASE")%> type="checkbox" id="mceg-c53" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_CROHNS_DISEASE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_CROHNS_DISEASE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.crohns-disease",sWebLanguage,"mceg-c53")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_COLITIS_ULCEROSA")%> type="checkbox" id="mceg-c54" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_COLITIS_ULCEROSA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_COLITIS_ULCEROSA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.colitis-ulcerosa",sWebLanguage,"mceg-c54")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_CHRONIC_DIARRHEA")%> type="checkbox" id="mceg-c55" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_CHRONIC_DIARRHEA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_CHRONIC_DIARRHEA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.chronic-diarrhea",sWebLanguage,"mceg-c55")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_INGUINAL_HERNIA")%> type="checkbox" id="mceg-c56" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_INGUINAL_HERNIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_INGUINAL_HERNIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.inguinal-hernia",sWebLanguage,"mceg-c56")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_NAVEL_HERNIA")%> type="checkbox" id="mceg-c57" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_NAVEL_HERNIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_NAVEL_HERNIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.umbilical-hernia",sWebLanguage,"mceg-c57")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_BOWEL_POLYPS")%> type="checkbox" id="mceg-c58" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_BOWEL_POLYPS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_BOWEL_POLYPS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.bowel-polyps",sWebLanguage,"mceg-c58")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_IRRITABEL_BOWEL")%> type="checkbox" id="mceg-c59" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_IRRITABEL_BOWEL" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_IRRITABEL_BOWEL;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.irritable-bowel",sWebLanguage,"mceg-c59")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_HEMORRHOIDS")%> type="checkbox" id="mceg-c60" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HEMORRHOIDS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_HEMORRHOIDS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.hemorrhoids",sWebLanguage,"mceg-c60")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_FISSURE")%> type="checkbox" id="mceg-c61" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_FISSURE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_FISSURE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.anal-fissura",sWebLanguage,"mceg-c61")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_ABCES")%> type="checkbox" id="mceg-c62" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_ABCES" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_ABCES;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.anal-abces",sWebLanguage,"mceg-c62")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_FISTULA")%> type="checkbox" id="mceg-c63" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_FISTULA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_ANAL_FISTULA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.anal-fistula",sWebLanguage,"mceg-c63")%></td>
                </tr>
                <tr>
                    <td class="admin2" colspan="4"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_FAECAL_INCONTINENTION")%> type="checkbox" id="mceg-c64" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_FAECAL_INCONTINENTION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_FAECAL_INCONTINENTION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.fecal-incontinention",sWebLanguage,"mceg-c64")%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.gastro.other-bowel-disorders",sWebLanguage)%></td>
                    <td class="admin2" colspan="3"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_BOWEL")%> type="text" class="text" size="90" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_BOWEL" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER_BOWEL" property="value"/>" onblur="limitLength(this);"></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_LIVER_STEATOSIS")%> type="checkbox" id="mceg-c65" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_LIVER_STEATOSIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_LIVER_STEATOSIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.liver-steatosis",sWebLanguage,"mceg-c65")%></td>
                    <td class="admin2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_LIVER_CIRRHOSIS")%> type="checkbox" id="mceg-c66" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_LIVER_CIRRHOSIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_LIVER_CIRRHOSIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.liver-cirrhosis",sWebLanguage,"mceg-c66")%></td>
                    <td class="admin2" colspan="2"><input <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_CHOLECYSTITIS")%> type="checkbox" id="mceg-c67" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_CHOLECYSTITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_CHOLECYSTITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.gastro.cholecystitis",sWebLanguage,"mceg-c67")%></td>
                </tr>
                <tr>
                    <td class="admin"><%=getTran("Web.Occup","medwan.common.remark",sWebLanguage)%></td>
                    <td class="admin2" colspan="3">
                        <textarea onKeyup="resizeTextarea(this,10);" <%=setRightClick("ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER")%> class="text" rows="2" cols="80" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_GASTRO_DIAGNOSIS_OTHER" property="value"/></textarea>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<%=ScreenHelper.alignButtonsStart()%>
    <INPUT class="button" type="button" name="saveButton" onClick="doSubmit();" value="<%=getTran("Web.Occup","medwan.common.record",sWebLanguage)%>">
    <INPUT class="button" type="button" value="<%=getTran("Web","Back",sWebLanguage)%>" onclick="if(checkSaveButton())){window.location.href='<c:url value='/healthrecord/editTransaction.do'/>?be.mxs.healthrecord.createTransaction.transactionType=<bean:write name="transaction" scope="page" property="transactionType"/>&be.mxs.healthrecord.transaction_id=currentTransaction&ts=<%=getTs()%>'}">
    <%=writeResetButton("transactionForm",sWebLanguage)%>
<%=ScreenHelper.alignButtonsStop()%>

<script>
  function doSubmit(){
    transactionForm.saveButton.disabled = true;
    document.transactionForm.submit();
  }

  document.getElementsByName('gastro-ras')[0].onclick();
</script>

</form>
<%=writeJSButtons("transactionForm", "document.getElementsByName('save')[0]")%>