<%@include file="/includes/validateUser.jsp"%>
<%@page errorPage="/includes/error.jsp"%>

<form name="transactionForm" method="POST" action='<c:url value="/healthrecord/updateTransaction.do"/>?ts=<%=getTs()%>' onclick="setSaveButton();" onkeyup="setSaveButton();">
   <bean:define id="transaction" name="be.mxs.webapp.wl.session.SessionContainerFactory.WO_SESSION_CONTAINER" property="currentTransactionVO"/>

    <input type="hidden" name="subClass" value="DERMATOLOGY"/>
    <input id="transactionId" type="hidden" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.transactionId" value="<bean:write name="transaction" scope="page" property="transactionId"/>"/>
    <input id="transactionType" type="hidden" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.transactionType" value="<bean:write name="transaction" scope="page" property="transactionType"/>"/>
    <input id="serverId" type="hidden" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.serverId" value="<bean:write name="transaction" scope="page" property="serverId"/>"/>
    <input type="hidden" readonly name="be.mxs.healthrecord.updateTransaction.actionForwardKey" value="/healthrecord/editTransaction.do?be.mxs.healthrecord.createTransaction.transactionType=<bean:write name="transaction" scope="page" property="transactionType"/>&be.mxs.healthrecord.transaction_id=currentTransaction&ts=<%=getTs()%>"/>
    <input type="hidden" readonly name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_DERMATOLOGIE_RAS" property="itemId"/>]>.value" value="medwan.common.false"/>

<script>
  function setTrue(itemType){
    var fieldName;
    fieldName = "currentTransactionVO.items.<ItemVO[hashCode="+itemType+"]>.value";
    document.getElementsByName(fieldName)[0].value = "medwan.common.true";
  }

  function setFalse(itemType){
    var fieldName;
    fieldName = "currentTransactionVO.items.<ItemVO[hashCode="+itemType+"]>.value";
    document.getElementsByName(fieldName)[0].value = "medwan.common.false";
  }
</script>

<table width="100%" class="list" cellspacing="0">
    <tr class="admin">
        <td><%=getTran("Web.Occup","medwan.healthrecord.anamnese.dermatologie",sWebLanguage)%></td>
        <td align="right" width="20%">
            <%=getLabel("Web.Occup","medwan.common.nothing-to-mention",sWebLanguage,"mced-c1")%>&nbsp;<input name="dermato-ras" type="checkbox" id="mced-c1" value="medwan.common.true" onclick="if (this.checked == true) {hide('dermato-details');setTrue('<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_DERMATOLOGIE_RAS" property="itemId"/>'); } else {show('dermato-details');setFalse('<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_DERMATOLOGIE_RAS" property="itemId"/>'); }">
        </td>
        <td align="right" width ="1%"><a href="#top" class="topbutton">&nbsp;</a></td>
    </tr>
    <tr id="dermato-details" style="display:none" width="100%">
        <td colspan="3" width="100%">
            <table width="100%" cellspacing="1">
                <tr class="admin">
                    <td colspan="6"><%=getTran("Web.Occup","medwan.healthrecord.anamnese",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_ROUGEUR")%> type="checkbox" id="mced-c2" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_ROUGEUR" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_ROUGEUR;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.rougeur",sWebLanguage,"mced-c2")%></td>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_ICTERE")%> type="checkbox" id="mced-c3" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_ICTERE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_ICTERE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.ictere",sWebLanguage,"mced-c3")%></td>
                    <td class="admin2" colspan="4"><input <%=setRightClick("[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_PRURIT")%> type="checkbox" id="mced-c4" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_PRURIT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_PRURIT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.prurit",sWebLanguage,"mced-4")%></td>
                </tr>
                <tr>
                    <td class="admin" colspan="2"><%=getTran("Web.Occup","medwan.healthrecord.anamnese.other",sWebLanguage)%></td>
                    <td class="admin2" colspan="4"><input <%=setRightClick("[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_OTHER")%> type="text" class="text" size="80" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_OTHER" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.ANAMNESE]ITEM_TYPE_OTHER" property="value"/>" onblur="validateText(this);limitLength(this);"></td>
                </tr>
                <tr class="admin">
                    <td colspan="6"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%>/td>
                </tr>
                <tr>
                    <td class="admin2" width="15%"><input <%=setRightClick("[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_PALEUR")%> type="checkbox" id="mced-c5" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_PALEUR" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_PALEUR;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.paleur",sWebLanguage,"mced-c5")%></td>
                    <td class="admin2" width="15%"><input <%=setRightClick("[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_ICTERE")%> type="checkbox" id="mced-c6" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_ICTERE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_ICTERE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.ictere",sWebLanguage,"mced-c6")%></td>
                    <td class="admin2" width="15%"><input <%=setRightClick("[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_CICATRICE")%> type="checkbox" id="mced-c7" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_CICATRICE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_CICATRICE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.cicatrice",sWebLanguage,"mced-c7")%></td>
                    <td class="admin2" width="15%"><input <%=setRightClick("[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_NAEVUS_SUSPECTE")%> type="checkbox" id="mced-c8" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_NAEVUS_SUSPECTE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_NAEVUS_SUSPECTE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.naevus-suspecte",sWebLanguage,"mced-c8")%></td>
                    <td class="admin2" width="15%"><input <%=setRightClick("[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_MACULES")%> type="checkbox" id="mced-c9" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_MACULES" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_MACULES;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.papules",sWebLanguage,"mced-c9")%></td>
                    <td class="admin2" width="*"><input <%=setRightClick("[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_ROUGEUR")%> type="checkbox" id="mced-c10" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_ROUGEUR" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.CLINICAL_EXAMNIATION]ITEM_TYPE_ROUGEUR;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.macules",sWebLanguage,"mced-c10")%></td>
                </tr>
                <tr class="admin">
                    <td colspan="6"><%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_LIPOME")%> type="checkbox" id="mced-c11" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_LIPOME" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_LIPOME;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.lipome",sWebLanguage,"mced-c11")%></td>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_URTICAIRE")%> type="checkbox" id="mced-c12" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_URTICAIRE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_URTICAIRE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.urticaire",sWebLanguage,"mced-c12")%></td>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_DERMATITE")%> type="checkbox" id="mced-c13" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_DERMATITE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_DERMATITE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.dermatite",sWebLanguage,"mced-c13")%></td>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_DERMATITE_DE_CONTACT")%> type="checkbox" id="mced-c14" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_DERMATITE_DE_CONTACT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_DERMATITE_DE_CONTACT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.dermatite-de-contact",sWebLanguage,"mced-c14")%></td>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_GALE")%> type="checkbox" id="mced-c15" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_GALE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_GALE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.gale",sWebLanguage,"mced-c15")%></td>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_PUCES")%> type="checkbox" id="mced-c16" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_PUCES" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_PUCES;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.puces",sWebLanguage,"mced-c16")%></td>
                </tr>
                <tr>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_VERRURES")%> type="checkbox" id="mced-c17" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_VERRURES" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_VERRURES;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.verrues",sWebLanguage,"mced-c17")%></td>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_CANDIDA")%> type="checkbox" id="mced-c18" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_CANDIDA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_CANDIDA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.candida",sWebLanguage,"mced-c18")%></td>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_ACNEE")%> type="checkbox" id="mced-c19" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_ACNEE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_ACNEE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.acne",sWebLanguage,"mced-c19")%></td>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_PSORIASIS")%> type="checkbox" id="mced-c20" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_PSORIASIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_PSORIASIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.psoriasis",sWebLanguage,"mced-c20")%></td>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_PITYRIASIS_VERSICOLOR")%> type="checkbox" id="mced-c21" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_PITYRIASIS_VERSICOLOR" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_PITYRIASIS_VERSICOLOR;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.pityriasis-versicolor",sWebLanguage,"mced-c21")%></td>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_ZONA")%> type="checkbox" id="mced-c22" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_ZONA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_ZONA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.zona",sWebLanguage,"mced-c22")%></td>
                </tr>
                <tr>
                    <td class="admin2" colspan="3"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_AFFECTION_ONGLES")%> type="checkbox" id="mced-c23" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_AFFECTION_ONGLES" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_AFFECTION_ONGLES;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.affection-ongles",sWebLanguage,"mced-c23")%></td>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_TUMEUR_BENIN")%> type="checkbox" id="mced-c24" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_TUMEUR_BENIN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_TUMEUR_BENIN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.tumeur",sWebLanguage,"mced-c24")%><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.tumeur.benin",sWebLanguage,"mced-c24")%></td>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_TUMEUR_MALIN")%> type="checkbox" id="mced-c25" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_TUMEUR_MALIN" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_TUMEUR_MALIN;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.tumeur",sWebLanguage,"mced-c25")%><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.tumeur.malin",sWebLanguage,"mced-c25")%></td>
                    <td class="admin2"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_MYCOSES")%> type="checkbox" id="mced-c26" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_MYCOSES" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_MYCOSES;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"><%=getLabel("Web.Occup","medwan.healthrecord.anamnese.dermatologie.mycoses",sWebLanguage,"mced-c26")%></td>
                </tr>
                <tr>
                    <td class="admin" colspan="2"><%=getTran("Web.Occup","medwan.healthrecord.anamnese.other",sWebLanguage)%></td>
                    <td class="admin2" colspan="4"><input <%=setRightClick("[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_OTHER")%> type="text" class="text" size="80" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_OTHER" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.[DERMATOLOGIE.DIAGNOSE]ITEM_TYPE_OTHER" property="value"/>" onblur="validateText(this);limitLength(this);"></td>
                </tr>
            </table>
        </td>
    </tr>
</table>

<%-- BUTTONS --%>
<%=ScreenHelper.alignButtonsStart()%>
    <INPUT class="button" type="button" name="save" onClick="doSubmit();" value="<%=getTran("Web.Occup","medwan.common.record",sWebLanguage)%>">
    <INPUT class="button" type="button" value="<%=getTran("Web","Back",sWebLanguage)%>" onclick="if (checkSaveButton('<%=sCONTEXTPATH%>','<%=getTran("Web.Occup","medwan.common.buttonquestion",sWebLanguage)%>')){window.location.href='<c:url value='/healthrecord/editTransaction.do'/>?be.mxs.healthrecord.createTransaction.transactionType=<bean:write name="transaction" scope="page" property="transactionType"/>&be.mxs.healthrecord.transaction_id=currentTransaction&ts=<%=getTs()%>'}">
    <%=writeResetButton("transactionForm",sWebLanguage)%>
<%=ScreenHelper.alignButtonsStop()%>

<script>
  function doSubmit(){
    document.transactionForm.saveButton.disabled = true;
    <%
        SessionContainerWO sessionContainerWO = (SessionContainerWO)SessionContainerFactory.getInstance().getSessionContainerWO(request,SessionContainerWO.class.getName());
        out.print(takeOverTransaction(sessionContainerWO, activeUser,"document.transactionForm.submit();"));
    %>
  }

  document.getElementsByName('dermato-ras')[0].onclick();
</script>

</form>
<%=writeJSButtons("transactionForm", "document.getElementsByName('save']")%>