<%@page errorPage="/includes/error.jsp"%>
<%@include file="/includes/validateUser.jsp"%>
<%
    
%>
<form name="transactionForm" id="transactionForm" method="POST" action='<c:url value="/healthrecord/updateTransaction.do"/>?ts=<%=getTs()%>' onclick="setSaveButton(event);" onkeyup="setSaveButton(event);">
    <bean:define id="transaction" name="be.mxs.webapp.wl.session.SessionContainerFactory.WO_SESSION_CONTAINER" property="currentTransactionVO"/>
	<%=checkPrestationToday(activePatient.personid,false,activeUser,(TransactionVO)transaction)%>
    <input type="hidden" id="transactionId" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.transactionId" value="<bean:write name="transaction" scope="page" property="transactionId"/>"/>
    <input type="hidden" id="transactionType" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.transactionType" value="<bean:write name="transaction" scope="page" property="transactionType"/>"/>
    <input type="hidden" id="serverId" name="currentTransactionVO.<TransactionVO[hashCode=<bean:write name="transaction" scope="page" property="transactionId"/>]>.serverId" value="<bean:write name="transaction" scope="page" property="serverId"/>"/>
    <input type="hidden" readonly name="be.mxs.healthrecord.updateTransaction.actionForwardKey" value="/healthrecord/manageClinicalExamination.do?be.mxs.healthrecord.createTransaction.transactionType=<bean:write name="transaction" scope="page" property="transactionType"/>&be.mxs.healthrecord.transaction_id=currentTransaction"/>
    <input type="hidden" readonly name="subClass" value=".ORL.ENDOCRINO"/>
    <input type="hidden" readonly name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CONTEXT_DEPARTMENT" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CONTEXT_DEPARTMENT" translate="false" property="value"/>"/>
    <input type="hidden" readonly name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CONTEXT_CONTEXT" translate="false" property="itemId"/>]>.value" value="<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_CONTEXT_CONTEXT" translate="false" property="value"/>"/>
    <%
        if (session.getAttribute("sessionCounter")==null){
            session.setAttribute("sessionCounter",new Integer(0));
        }
        else {
            session.setAttribute("sessionCounter",new Integer(((Integer)session.getAttribute("sessionCounter")).intValue()+1));
        }
        session.setAttribute("sessionURL","/healthrecord/template.jsp?be.mxs.healthrecord.transaction_id=currentTransaction&Page="+customerInclude("/healthrecord/orl_endocrino.jsp")+"&message=true");
        if (request.getParameter("message")!=null){
            out.print("<script>alert('"+getTran("Web.Occup","medwan.common.do-not-use-back",sWebLanguage)+"');</script>");
        }
    %>
    <script>
      function setTrue(itemType){
        var fieldName;
        fieldName = "currentTransactionVO.items.<ItemVO[hashCode="+itemType+"]>.value";
        document.getElementsByName(fieldName)[0].value = "medwan.common.true";
      }

      function setFalse(itemType){
        var fieldName;
        fieldName = "currentTransactionVO.items.<ItemVO[hashCode="+itemType+"]>.value";
        document.getElementsByName(fieldName)[0].value = "medwan.common.false";
      }
    </script>
    <br>
<%-- ORL-endocrino -------------------------------------------------------------------------------%>
<table border='0' width='100%' cellspacing="1" cellpadding="0" class="list">
    <tr class="admin">
        <td colspan="4">ORL-endocrino</td>
    </tr>
    <tr>
        <td class="admin" width="<%=sTDAdminWidth%>" rowspan="2"/>
        <td class="admin2" width="200"><input <%=setRightClick("ITEM_TYPE_ORL_ANAMNESIS_OTITIS")%> type="checkbox" id="orle-c1" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_OTITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_OTITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.otite",sWebLanguage,"orle-c1")%></td>
        <td class="admin2" width="200"><input <%=setRightClick("ITEM_TYPE_ORL_ANAMNESIS_ACOUPHENE")%> type="checkbox" id="orle-c2" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_ACOUPHENE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_ACOUPHENE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.acouphene",sWebLanguage,"orle-c2")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ORL_ANAMNESIS_AUDITIVE_LOSS")%> type="checkbox" id="orle-c3" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_AUDITIVE_LOSS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_AUDITIVE_LOSS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.perte-auditive",sWebLanguage,"orle-c3")%></td>
    </tr>
    <tr>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ORL_ANAMNESIS_EQUILIBRE_DISORDER")%> type="checkbox" id="orle-c4" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_EQUILIBRE_DISORDER" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_EQUILIBRE_DISORDER;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.trouble-equilibre",sWebLanguage,"orle-c4")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ORL_ANAMNESIS_NASAL_THROWING")%> type="checkbox" id="orle-c5" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_NASAL_THROWING" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_NASAL_THROWING;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.jetage-nasal",sWebLanguage,"orle-c5")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ORL_ANAMNESIS_VERTIGO")%> type="checkbox" id="orle-c6" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_VERTIGO" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_ANAMNESIS_VERTIGO;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.vertigo",sWebLanguage,"orle-c6")%></td>
    </tr>
    <%-- CLINICAL EXAM --%>
    <tr>
        <td colspan="4" class="clinical"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%></td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.ORL.ganglions-lymphatiques",sWebLanguage)%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ORL_CLINICAL_EXAMINATION_LYMPHATIC_GANGLIA_SUBMAXILLARY")%> type="checkbox" id="orle-c7" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_CLINICAL_EXAMINATION_LYMPHATIC_GANGLIA_SUBMAXILLARY" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_CLINICAL_EXAMINATION_LYMPHATIC_GANGLIA_SUBMAXILLARY;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.ganglions-lymphatiques.sous-maxillaires",sWebLanguage,"orle-c7")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ORL_CLINICAL_EXAMINATION_LYMPHATIC_GANGLIA_NECK")%> type="checkbox" id="orle-c8" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_CLINICAL_EXAMINATION_LYMPHATIC_GANGLIA_NECK" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_CLINICAL_EXAMINATION_LYMPHATIC_GANGLIA_NECK;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.ganglions-lymphatiques.cou",sWebLanguage,"orle-c8")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ORL_CLINICAL_EXAMINATION_LYMPHATIC_RETRO_AURICULAR")%> type="checkbox" id="orle-c9" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_CLINICAL_EXAMINATION_LYMPHATIC_RETRO_AURICULAR" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_CLINICAL_EXAMINATION_LYMPHATIC_RETRO_AURICULAR;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.ganglions-lymphatiques.retro-auriculaires",sWebLanguage,"orle-c9")%></td>
    </tr>
    <%-- DIAGNOSE --%>
    <tr>
        <td  colspan="4" class="clinical"><%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.ORL.otite-externe",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_EXTERNA_RIGHT")%> type="checkbox" id="orle-c10" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_EXTERNA_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_EXTERNA_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"orle-c10")%>
            <input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_EXTERNA_LEFT")%>  type="checkbox" id="orle-c11" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_EXTERNA_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_EXTERNA_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"orle-c11")%>
        </td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.ORL.otite-interne",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_INTERNA_RIGHT")%> type="checkbox" id="orle-c12" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_INTERNA_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_INTERNA_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"orle-c12")%>
            <input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_INTERNA_LEFT")%>  type="checkbox" id="orle-c13" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_INTERNA_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_OTITIS_INTERNA_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"orle-c13")%>
        </td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.ORL.tympan-perfore",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_TYMPAN_PERFORATION_RIGHT")%> type="checkbox" id="orle-c14" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_TYMPAN_PERFORATION_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_TYMPAN_PERFORATION_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"orle-c14")%>
            <input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_TYMPAN_PERFORATION_LEFT")%>  type="checkbox" id="orle-c15" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_TYMPAN_PERFORATION_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_TYMPAN_PERFORATION_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"orle-c15")%>
        </td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.ORL.bouchon-de-cerumen",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_CERUMEN_RIGHT")%> type="checkbox" id="orle-c16" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_CERUMEN_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_CERUMEN_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"orle-c16")%>
            <input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_CERUMEN_LEFT")%>  type="checkbox" id="orle-c17" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_CERUMEN_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_CERUMEN_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"orle-c17")%>
        </td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.ORL.surdite-professionnelle",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_PROFESSIONAL_DEAFNESS_RIGHT")%> type="checkbox" id="orle-c18" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_PROFESSIONAL_DEAFNESS_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_PROFESSIONAL_DEAFNESS_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"orle-c18")%>
            <input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_PROFESSIONAL_DEAFNESS_LEFT")%>  type="checkbox" id="orle-c19" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_PROFESSIONAL_DEAFNESS_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_PROFESSIONAL_DEAFNESS_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"orle-c19")%>
        </td>
    </tr>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.healthrecord.ORL.hypoacousie",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_HYPOACCUSY_RIGHT")%> type="checkbox" id="orle-c20" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_HYPOACCUSY_RIGHT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_HYPOACCUSY_RIGHT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.right",sWebLanguage,"orle-c20")%>
            <input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_HYPOACCUSY_LEFT")%>  type="checkbox" id="orle-c21" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_HYPOACCUSY_LEFT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_HYPOACCUSY_LEFT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.common.left",sWebLanguage,"orle-c21")%>
        </td>
    </tr>
    <tr>
        <td class="admin" rowspan="2"/>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_SINUSITIS")%> type="checkbox" id="orle-c22" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_SINUSITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_SINUSITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.sinusite",sWebLanguage,"orle-c22")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_RHINITIS")%> type="checkbox" id="orle-c23" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_RHINITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_RHINITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.rhinite",sWebLanguage,"orle-c23")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_PHARYNGITIS")%> type="checkbox" id="orle-c24" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_PHARYNGITIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_PHARYNGITIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.pharyngite",sWebLanguage,"orle-c24")%></td>
    </tr>
    <tr>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_NASAL_SEPTUM_DEVIATION")%> type="checkbox" id="orle-c26" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_NASAL_SEPTUM_DEVIATION" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_NASAL_SEPTUM_DEVIATION;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.deviation-cloison-nasale",sWebLanguage,"orle-c26")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_DENTAL_CARE_NEEDED")%> type="checkbox" id="orle-c27" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_DENTAL_CARE_NEEDED" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_DENTAL_CARE_NEEDED;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.dents-a-soigner",sWebLanguage,"orle-c27")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_ADENOID_VEGETATIONS")%> type="checkbox" id="orle-c25" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_ADENOID_VEGETATIONS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_ADENOID_VEGETATIONS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.ORL.hypertrophie-des-amygdales",sWebLanguage,"orle-c25")%></td>
    </tr>
    <%-- REMARK --%>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.common.remark",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <textarea onKeyup="resizeTextarea(this,10);limitChars(this,255);" <%=setRightClick("ITEM_TYPE_ORL_DIAGNOSIS_OTHER")%> class="text" rows="2" cols="80" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_OTHER" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ORL_DIAGNOSIS_OTHER" property="value"/></textarea>
        </td>
    </tr>
</table>
<br>
<%-- Endocrinologie ------------------------------------------------------------------------------%>
<table border='0' width='100%' cellspacing="1" cellpadding="0" class="list">
    <tr class="admin">
        <td colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.anamnese.endocrinologie",sWebLanguage)%></td>
    </tr>
    <tr>
        <td class="admin"/>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ENDOCRINO_ANAMNESIS_POLYURIA")%> type="checkbox" id="orle-c28" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_ANAMNESIS_POLYURIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_ANAMNESIS_POLYURIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.endocrino.polyuria",sWebLanguage,"orle-c28")%></td>
        <td class="admin2" colspan="2"><input <%=setRightClick("ITEM_TYPE_ENDOCRINO_ANAMNESIS_POLYDIPSIA")%> type="checkbox" id="orle-c29" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_ANAMNESIS_POLYDIPSIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_ANAMNESIS_POLYDIPSIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.endocrino.polydypsia",sWebLanguage,"orle-c29")%></td>
    </tr>
    <tr>
        <td class="clinical" colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.clinical-examination",sWebLanguage)%></td>
    </tr>
    <tr>
        <td class="admin"/>
        <td class="admin2" colspan="3"><input <%=setRightClick("ITEM_TYPE_ENDOCRINO_CLINICAL_EXAMINATION_THYROID_ENLARGEMENT")%> type="checkbox" id="orle-c30" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_CLINICAL_EXAMINATION_THYROID_ENLARGEMENT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_CLINICAL_EXAMINATION_THYROID_ENLARGEMENT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.endocrino.thyroid-enlargement",sWebLanguage,"orle-c30")%></td>
    </tr>
    <%-- DIAGNOSE --%>
    <tr>
        <td class="clinical" colspan="4"><%=getTran("Web.Occup","medwan.healthrecord.diagnose",sWebLanguage)%></td>
    </tr>
    <tr>
        <td class="admin" width="<%=sTDAdminWidth%>" rowspan="4"/>
        <td class="admin2" width="200"><input <%=setRightClick("ITEM_TYPE_ENDOCRINO_DIAGNOSIS_NIDDM")%> type="checkbox" id="orle-c31" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_NIDDM" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_NIDDM;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.endocrino.niddm",sWebLanguage,"orle-c31")%></td>
        <td class="admin2" width="200"><input <%=setRightClick("ITEM_TYPE_ENDOCRINO_DIAGNOSIS_IDDM")%> type="checkbox" id="orle-c32" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_IDDM" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_IDDM;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.endocrino.iddm",sWebLanguage,"orle-c32")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ENDOCRINO_DIAGNOSIS_GOITRE")%> type="checkbox" id="orle-c33" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_GOITRE" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_GOITRE;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.endocrino.goitre",sWebLanguage,"orle-c33")%></td>
    </tr>
    <tr>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ENDOCRINO_DIAGNOSIS_HYPOTHYROIDIA")%> type="checkbox" id="orle-c34" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_HYPOTHYROIDIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_HYPOTHYROIDIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.endocrino.hypothyroidia",sWebLanguage,"orle-c34")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ENDOCRINO_DIAGNOSIS_HYPERTHYROIDIA")%>  type="checkbox" id="orle-c35" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_HYPERTHYROIDIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_HYPERTHYROIDIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.endocrino.hyperthyroidia",sWebLanguage,"orle-c35")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ENDOCRINO_DIAGNOSIS_NODULAR_THYROID_SUFFERING")%> type="checkbox" id="orle-c36" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_NODULAR_THYROID_SUFFERING" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_NODULAR_THYROID_SUFFERING;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.endocrino.nodular-thyroid-suffering",sWebLanguage,"orle-c36")%></td>
    </tr>
    <tr>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ENDOCRINO_DIAGNOSIS_HYPOPHYSIS")%> type="checkbox" id="orle-c37" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_HYPOPHYSIS" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_HYPOPHYSIS;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.endocrino.hypophysis",sWebLanguage,"orle-c37")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ENDOCRINO_DIAGNOSIS_GYNECOMASTIA")%> type="checkbox" id="orle-c38" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_GYNECOMASTIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_GYNECOMASTIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.endocrino.gynecomastia",sWebLanguage,"orle-c38")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ENDOCRINO_DIAGNOSIS_HYPERCHOLESTEROLAEMIA")%> type="checkbox" id="orle-c39" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_HYPERCHOLESTEROLAEMIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_HYPERCHOLESTEROLAEMIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.endocrino.hypercholesterolemia",sWebLanguage,"orle-c39")%></td>
    </tr>
    <tr>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ENDOCRINO_DIAGNOSIS_HYPERTRIGLYCERIDAEMIA")%> type="checkbox" id="orle-c40" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_HYPERTRIGLYCERIDAEMIA" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_HYPERTRIGLYCERIDAEMIA;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.endocrino.hypertriglyceridemia",sWebLanguage,"orle-c40")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ENDOCRINO_DIAGNOSIS_GOUT")%> type="checkbox" id="orle-c41" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_GOUT" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_GOUT;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.endocrino.gout",sWebLanguage,"orle-c41")%></td>
        <td class="admin2"><input <%=setRightClick("ITEM_TYPE_ENDOCRINO_DIAGNOSIS_SURRENALES")%> type="checkbox" id="orle-c42" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_SURRENALES" property="itemId"/>]>.value" <mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_SURRENALES;value=medwan.common.true" property="value" outputString="checked"/> value="medwan.common.true"/><%=getLabel("Web.Occup","medwan.healthrecord.endocrino.gout",sWebLanguage,"orle-c42")%></td>
    </tr>
    <%-- REMARK --%>
    <tr>
        <td class="admin"><%=getTran("Web.Occup","medwan.common.remark",sWebLanguage)%></td>
        <td class="admin2" colspan="3">
            <textarea onKeyup="resizeTextarea(this,10);limitChars(this,255);" <%=setRightClick("ITEM_TYPE_ENDOCRINO_DIAGNOSIS_OTHER")%> class="text" rows="2" cols="80" name="currentTransactionVO.items.<ItemVO[hashCode=<mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_OTHER" property="itemId"/>]>.value"><mxs:propertyAccessorI18N name="transaction.items" scope="page" compare="type=be.mxs.common.model.vo.healthrecord.IConstants.ITEM_TYPE_ENDOCRINO_DIAGNOSIS_OTHER" property="value"/></textarea>
        </td>
    </tr>
    <tr>
        <td class="admin"/>
        <td class="admin2" colspan="3">
            <INPUT class="button" type="button" name="saveButton" id="save" onClick="doSubmit();" value="<%=getTranNoLink("Web.Occup","medwan.common.record",sWebLanguage)%>">
            <INPUT class="button" type="button" value="<%=getTranNoLink("Web","Back",sWebLanguage)%>" onclick="if(checkSaveButton()){window.location.href='<c:url value='/healthrecord/editTransaction.do'/>?be.mxs.healthrecord.createTransaction.transactionType=<bean:write name="transaction" scope="page" property="transactionType"/>&be.mxs.healthrecord.transaction_id=currentTransaction&ts=<%=getTs()%>'}">
        </td>
    </tr>
</table>
<script>
  function doSubmit(){
    transactionForm.saveButton.disabled = true;
    document.transactionForm.submit();
  }
</script>
</form>
<%=writeJSButtons("transactionForm","saveButton")%>